### ISSUE TITLE
PVP violation?

### ISSUE THREAD

**Issue by tomjaguarpaw** [tathougies/beam#1]
It seems that beam violates the PVP.  Version 0.3.0.0 has `QExpr` with one type parameter.  In version 0.3.2.0 it has two.

**Comment by tathougies** [comment]
Thanks for the catch. I'm a bit new to package maintenance. I think the fix be to bump to 0.4? Is that right?

**Comment by tomjaguarpaw** [comment]
Yes, that would work.

**Comment by tathougies** [comment]
Fixed in git now, and will upload to hackage. Thanks again!
