### ISSUE TITLE
Use of OFFSET and LIMIT together are not enforced

### ISSUE THREAD

**Issue by sajidanower23** [tathougies/beam#106]
When doing an `OFFSET` in SQLite, the `LIMIT` must be set explicitly. If there are no limits, then a negative number (typically -1) is used.
This also means that in Beam, when using the function `offset_`, the `limit_` function must always be used, otherwise, it is guaranteed to cause a run-time exception.
On a higher level, the solution, I suppose, is that Beam could infer a lack of `limit_` as `limit_ (-1)`, unless this can be ensured at a type-level.

**Comment by tathougies** [comment]
Thanks for reporting. This is a very straightforward fix. No need for type system anything.
