### ISSUE TITLE
runInsertReturningList drops failures in beam-postgres

### ISSUE THREAD

**Issue by tathougies** [tathougies/beam#112]
runInsertReturningList drops postgres exceptions on failure. For example, if the beam and database schemas do not match, an exception should be raised instead of an empty list

**Comment by 3noch** [comment]
I have noticed this but wasn't sure exactly what was going on. Thanks for helping me understand.

**Comment by tathougies** [comment]
Added test for this in cc8f02fed760c1713519e7b0affb13588c739d49
