### ISSUE TITLE
Can't generate lenses at all with the code from the tutorial

### ISSUE THREAD

**Issue by reactormonk** [tathougies/beam#114]
https://gist.github.com/reactormonk/a528ac5828e5312896bd5fcb99f07687

**Comment by tathougies** [comment]
Looks like a change in GHC's typechecker. I'm not sure if this will be fixable or not. In the meantime, `Control.Lens`'s template haskell generation should still work.

**Comment by tathougies** [comment]
I think you need to add `-XImpredicativeTypes`, and this should compile.  This is a change in the type checker in 8.2, and I'm updating the documentation to reflect this.
