### ISSUE TITLE
Representing Maybe in migration

### ISSUE THREAD

**Issue by sajidanower23** [tathougies/beam#122]
A minimal example can be found in the file https://github.com/tathougies/beam/blob/3553ba7edcc3b85749530262fc12af6584061fa2/beam-postgres/examples/Pagila/Schema/V0001.hs#L33

We have a column in a table 
`record_time :: C f (Maybe LocalTime)`
When I try to build this, I get the error 
```
• Couldn't match type ‘Maybe LocalTime’ with ‘LocalTime’
```

Relevant table:
```haskell
data WhenT f = When
  { record_time                :: C f (Maybe LocalTime) 
  -- ... other columns
  }
  deriving Generic
```

In migration script:
```haskell
When
     (field "record_time" timestamptz)
     -- other columns, and there is a ``notNull`` when it's not a `Maybe`
```

In our `stack.yaml`, the Beam snapshot we are using is
```yaml
commit: 3553ba7edcc3b85749530262fc12af6584061fa2
```
Is there another way to represent a `Maybe`? I think the V0001.hs file is not building anymore either.

**Comment by sajidanower23** [comment]
Having looked at #123 , I figured that I could just use `maybeType`, and that typechecks.
I am happy to put in a Pull Request to fix up the examples and perhaps add some docs for the migration framework.

**Comment by tathougies** [comment]
The docs for the migrations framework are either out-of-date or not written, but the reference documentation (now on [hackage](https://hackage.haskell.org/package/beam-migrate-0.2.0.0/docs/Database-Beam-Migrate-SQL-Tables.html#v:maybeType)) might make it clearer,
