### ISSUE TITLE
beam on hackage causes bad build plans on GHC 7.8

### ISSUE THREAD

**Issue by gwils** [tathougies/beam#124]
The (deprecated) beam package on hackage causes bad build plans on GHC 7.8 on all versions. The cause is that beam uses `Data.Void`, which had not been added to base yet, so it would have needed to declare a dependency on the `void` package in its cabal file.

https://matrix.hackage.haskell.org/package/beam

Please use hackage metadata revisions to fix this. Revisions are [intentionally not powerful enough](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md) to add the missing dependency on void, so the best we can do is tighten the base constraint so that the package will try not to build on GHC 7.8.

To achieve this please change the dependency on base from `>=4.7 && <4.9` to `>=4.8 && <4.9`

I understand that this package is now deprecated, so it's not the end of the world if you don't decide to do this, but at the same time, it won't take very long to do :)

**Comment by tathougies** [comment]
I'll try it... thanks for the report.

**Comment by gwils** [comment]
Your revision on 0.3.2.0 has done the trick for that version :)
Please do the same for 0.3.1.0 and 0.3.0.0
