### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by mightybyte** [tathougies/beam#13]
What's the state of Postgres support?  In the tutorial it said that it should work with all HDBC databases.  But when I pass the output of `dumpSchema` to Postgres, I get errors.  Is this a bug or does it still need a Postgres backend.  If the latter, what would be necessary to do that?

**Comment by tathougies** [comment]
The problem here is the use of `AutoId` in the tables, which generate an AUTOINCREMENT constraint. In the branch travis/explicit-backends, I've started work on making how each type is mapped to SQL dependent on the backend chosen, but it's not there yet.

**Comment by tathougies** [comment]
Postgres now has its own dedicated integration package (beam-Postgres) in master. Closing this one out
