### ISSUE TITLE
in_ doesn't seem to support query expressions, only concrete values.

### ISSUE THREAD

**Issue by iand675** [tathougies/beam#133]
I'm trying to write a query that deletes some subset of values that are selected from the DB without reading them into the Haskell process, but running into difficulties. Here's a slightly contrived example of what I'm trying to write:

``` haskell
delete (uploadsTable db) $ \upload -> in_ (uploadId upload) 
  [subselect_ $ 
    filter_ (\key -> uploadCreatedAt key <. auto_ (val_ threeDaysAgo)) $
    limit_ 500 $ -- a normal delete query doesn't support limit
    all_ (uploadsTable db)]
```

However, `in_` takes a list of expressions, `[QGenExpr context syntax s a]`, that seems to not be amenable to accepting a subselect as an argument of the list.

It sort of vaguely looks like `anyOf_` might be able to support this, but I confess I'm having a hard time getting the types to line up there either. Do you have any advice for how to write this sort of query?

**Comment by tathougies** [comment]
Yes, `anyOf_` is probably what you want.  You'd do something like

```haskell
delete (uploadsTable db) $ \upload ->
    uploadId upload ==*. 
        anyOf_ (filter_ (\key -> uploadCreatedAt key <. auto_ (val_ threeDaysAgo)) $
                limit_ 500 $ -- a normal delete query doesn't support limit
                all_ (uploadsTable db))
```

The `(==*.)` operator is the quantified equality operator, which allows you to use `anyOf_` or `allOf_` (rather than a simple scalar).

**Comment by tathougies** [comment]
@iand675 Does this answer your question?
