### ISSUE TITLE
Support for trim in core

### ISSUE THREAD

**Issue by mulderr** [tathougies/beam#145]
Some variations I've seen:

1. `TRIM(x)`, `TRIM(x, y)`
1. `LTRIM(x)`, `LTRIM(x, y)`
1. `RTRIM(x)`, `RTRIM(x, y)`
1. `TRIM([BOTH|LEADING|TRAILING] [char] [FROM] string)` (single-char)
1. `TRIM([BOTH|LEADING|TRAILING] [string] [FROM] string)` (full)

Note, if `y = 'abc'` then the two argument versions work like `trim([both|leading|trailing] 'a,b,c' from x)`.

Compatibility matrix (please correct me, it's hard to find reliable info):

| Version | Standard | PostgreSQL | SQLite | MySQL | Oracle | SQL Server |
| --- | --- | --- | --- | --- | --- | --- |
| TRIM(x) | SQL-92 | Y | Y | Y | Y | Y/N* |
| LTRIM(x) | - | Y | Y | Y | Y | Y |
| RTRIM(x) | - | Y | Y | Y | Y | Y |
| Two-arg | - | Y | Y | N | N | N |
| single-char | SQL-92 | Y | N | Y | Y | Y/N* |
| full | ? | Y | N | Y*** | N** | Y/N* |

\* SQL Server versions prior to 2017 do not have TRIM
\*\* Oracle only supports the one character version (ORA-30001), use replace
\*\*\* MySQL does not support lists like 'a,b,c'

I think the following would make sense as a common ground:
```
TRIM(x) == trim_ x
RTRIM(x) == rtrim_ x
LTRIM(x) == ltrim_ x
```

That is assuming we don't care about old versions of SQL Server which apparently didn't care about the standard so...

Edit:

Apparently LTRIM and RTRIM are also non standard. At least I cannot find any mention of them in whats publicly available. So we may stick to just TRIM(x) in core and leave the rest to be implemented in backends.

**Comment by tathougies** [comment]
I'd be happy to accept a PR adding `TRIM` to the standard expression syntax.

`RTRIM` and `LTRIM` are non-standard, I believe. Non-standard things that are common enough to be useful across backends can be placed in the `BeamExtensions` module.

**Comment by mulderr** [comment]
Yep, `TRIM(LEADING...)` and `TRIM(TRAILING...)` are standard and semantically they should  be the same as `LTRIM` and `RTRIM` but in practice they're not always interchangeable because SQLite and older SQL Server, as an example, support the latter but not the former.
