### ISSUE TITLE
SELECT .... FOR UPDATE Support Planned?

### ISSUE THREAD

**Issue by SamProtas** [tathougies/beam#152]
I couldn't find anything in the docs/code to indicate this was currently possible or considered yet. Is this feature planned?

Postgres in particular has a lot of useful variations of `lock strength` and `NOWAIT / SKIP LOCKED`.

**Comment by tathougies** [comment]
Sure it's planned, but I can't make any promises. This would actually be a straightforward implementation, but someone just needs to do it. The codebase is quite flexible. I'd be happy to provide in-depth assistance if you're interested in implementing this. Otherwise, I promise I'll do it at some point in the future :)

**Comment by SamProtas** [comment]
I can take a stab at it sure. Any guidance you could provide would be appreciated as I haven't actually used Beam yet. I just came across it a few days ago, but I'm hoping this will become my go-to database library for Haskell as it seems much nicer than alternatives I'm used to. So thanks for taking it this far already!

**Comment by tathougies** [comment]
Sure... I would probably create a new postgres-specific `select` function in [Syntax.hs](https://github.com/tathougies/beam/blob/master/beam-postgres/Database/Beam/Postgres/Syntax.hs#L1273). It will overlap the one already defined in `beam-core`, but that's alright.

You can follow the example of `insert` (linked above). Basically, you can start from the default `beam-core` [`select`](https://github.com/tathougies/beam/blob/master/beam-core/Database/Beam/Query.hs#L113) function, and add arguments for the postgres-specific parts (the locking strategy, etc). For each new piece of syntax added, create a newtype wrapper (the way we do with `PgInsertOnConflict`, etc) and provide values for their construction. 

For the postgres backend, `buildSqlQuery` will return a value of `PgSelectSyntax`, which is just a newtype wrapper over `PgSyntax`. Take this value out of `PgSelectSyntax` and you can monoidally append all your new concrete syntax pieces directly.

So, as a brief skeleton:

```haskell
newtype PgSelectLockingClauseSyntax = PgSelectLockingClauseSyntax  { fromPgSelectLockingClause :: PgSyntax }

pgForUpdate :: PgSelectLockingClauseSyntax
pgForUpdate = PgSelectLockingClauseSyntax (emit "FOR UPDATE")

select :: <copy over the type signature>
select query pgLocking =
  let PgSelectSyntax selectStmtSyntax = buildSqlQuery "t" q
      selectStmtSyntax' =
        PgSelectSyntax
          (selectStmtSyntax <>
           case pgLocking of
             Nothing -> mempty
             Just (PgSelectLockingClauseSyntax lock) -> emit " " <> lock)
  in SqlSelect selectStmtSyntax'
```

**Comment by tathougies** [comment]
I would begin by adding a new function to build the postgres select syntax. This is stored in the type `PgSelectSyntax`, which is a newtype wrapper over `PgSyntax`. I would add a function to build a select statement with a locking clause. This would also involve defining a new syntax for the locking clause.

Here's a skeleton of what to do:

```haskell
newtype PgSelectLockingClauseSyntax = PgSelectLockingClauseSyntax { fromPgSelectLockingClause :: PgSyntax }

pgForUpdate :: PgSelectLockingClauseSyntax
pgForUpdate = PgSelectLockingClauseSyntax (emit "FOR UPDATE")

pgSelectStmt :: <copy over the type signature of selectStmt in database/beam/backend/sql/sql92.hs>
pgSelectStmt tbl order limit offset locking =
  PgSelectSyntax $
  mappend (<copy over the body of the postgres instance of 'selectStmt'>)
    (maybe mempty fromPgSelectLockingClasue locking)
```

Then, we can talk about how to integrate that with the rest of the library.
