### ISSUE TITLE
Creating DB schema on the first run?

### ISSUE THREAD

**Issue by reygoch** [tathougies/beam#154]
So, I know there is migration library, but I'm wondering if it's possible to use it to create all the required tables in an empty database. Right now, from what I understand, I have to create the initial schema by using SQL / DDL and beam can only do CRUDE operations on it.

Am I missing something?

**Comment by tathougies** [comment]
`beam-migrate` is strictly more advanced than any other Haskell library (I know of at least), both in the coarseness of migrations and in its ability to automatically migrate one schema to another. `beam-migrate` allows you to express most of the common DDL operations in a type-safe manner. This is useful for writing explicit migrations.

That being said, my opinion is that automatic migrations are an anti-pattern. While convenient for development, they can easily bork any kind of production environment. For that reason, I probably will never make them magically happen.

Still, it is straightforward to have beam automatically generate migrations from a `CheckedDatabaseSettings` object and a description of the current schema. All the functions are there, and the hackage documentation describes each, but there is some code golf necessary (I'll probably add a shortcut in the near future).

```haskell
import Database.Beam.Migrate
import Database.Beam.Migrate.Backend
import Database.Beam.Migrate.Actions (heuristicSolver)
import qualified Database.Beam.Postgres.Migrate as Postgres (migrationBackend)

myDatabase :: CheckedDatabaseSettings Postgres MyDatabase

doMigrate :: Connection -> Pg ()
doMigrate conn = withDatabase conn $ do
    actualSchema <- backendGetDbConstraints Postgres.migrationBackend
    let expectedSchema = collectChecks myDatabase
        solver = heuristicSolver (backendActionProvider Postgres.migrationBackend) actualSchema expectedSchema
    case finalSolution solver of
      Solved cmds -> putStrLn "Migrating database..." >> mapM_ runNoAction cmds
      NoSolution candidates -> putStrLn "Unable to auto-migrate"
```

An explanation of the above:

* First we determine the current database schema in the database (`backendGetDbConstraints Postgres.migrationBackend`)
* Then, we get the expected schema from the `CheckedDatabaseSettings` object
* The `heuristicSolver` constructs a migration solver that will attempt to figure out a set of actions to take based on the default actions beam knows to do in postgres
* `finalSolution` will use the default solving strategy to figure out a viable migration. If it does, it returns `Solved cmds`, where `cmds` is a list of SQL commands that can be executed directly against the database (that's what we do with `runNoReturn`)
* If there is no migration that beam can figure, it returns `NoSolution` along with several schemas that are the "closest" to the one requested.

**Comment by adithep** [comment]
What I get is 

```
Cannot use record selector ‘backendGetDbConstraints’ as a function due to escaped type variables
      Probable fix: use pattern-matching syntax instead
```

**Comment by tathougies** [comment]
Oh, yeah, you probably need to use pattern matching instead to get the `backendGetDbConstraints` field. I may add a convenience function to make this easier in the future.

Does that make sense?-

**Comment by tathougies** [comment]
You should now be able to use 'autoMigrate` from `Database.Beam.Migrate.Simple` to automatically migrate a database. The function will fail if there is any potential data loss.
