### ISSUE TITLE
Postgres backend generates invalid SQL on insert with empty list

### ISSUE THREAD

**Issue by saevarb** [tathougies/beam#156]
Here's a minimal example:

```haskell
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE TypeFamilies #-}

module BugTest where

import Data.Text(Text)

import Database.Beam
import Database.Beam.Postgres (connectPostgreSQL, Postgres)

data SimpleTable f
  = SimpleTable
  { simpletblField1 :: Columnar f (Auto Int)
  , simpletblField2 :: Columnar f Text
  }
  deriving Generic
instance Beamable SimpleTable

instance Table SimpleTable where
  data PrimaryKey SimpleTable f = SimpleTableId (Columnar f (Auto Int)) deriving Generic
  primaryKey = SimpleTableId <$> simpletblField1
instance Beamable (PrimaryKey SimpleTable)

data MyDb f =
  MyDb { mydbSimpleTable :: f (TableEntity SimpleTable) } deriving Generic
instance Database MyDb


deriving instance Show (SimpleTable Identity)


myDb :: DatabaseSettings Postgres MyDb
myDb = defaultDbSettings

test :: IO ()
test = do
    -- create a database named test
    -- table creation not necessary to see debug output
    conn <- connectPostgreSQL "dbname='test'"
    res <- withDatabaseDebug putStrLn conn $ do
        runInsert $ insert (mydbSimpleTable myDb) $ insertValues []
    print res
    return ()

````

The generated SQL is `INSERT INTO "simple_table"("field1", "field2") VALUES `. 
I'm not SQL expert at all, so I did some research on what the normal behavior should be with an empty insert. 

It seems `INSERT INTO .. VALUES ()` is also invalid syntax, so that clearly isn't an option. But it seems that it's possible to generate `INSERT INTO .. DEFAULT VALUES`. However, given that this means actually inserting a row into the table if the table doesn't contain any non-nullable columns and/or all columns have a default value, this may be counter-intuitive to a Haskell programmer. I know that I would personally expect an insert with an empty list as argument would simply not cause an insert at all; inserting a list with `n` elements should (in an ideal scenario) cause `n` new rows to be inserted.

I'm not sure what the best solution would be here. Is it possible to generate just a no-op? But it may also be a good idea to provide another version of `runInsert` or `insert` which would actually create a row with the default values, since I can imagine that behavior being useful as well.

**Comment by mulderr** [comment]
I think this narrows down to a choice between:

* make `insertValues []` a noop - this would be consistent with a recent fix for #149 
* have `insertValues` take `NonEmpty a` instead of `[a]`

SQL-92 says `DEFAULT VALUES` is equivalent to `VALUES (DEFAULT, . . . )` so neither of the above necessarily causes any loss in expressivity.
