### ISSUE TITLE
PostgreSQL backend produces syntax error

### ISSUE THREAD

**Issue by ajmccluskey** [tathougies/beam#157]
The PostgreSQL backend produces a syntax error when `Auto Nothing` is used in a `SELECT` that is part of an `INSERT`. Specifically, the generated SQL uses `DEFAULT` in the `SELECT`, which is invalid.

The query function is

```haskell
insertUserIfNotPresent
  :: Connection
  -> Text
  -> IO (Maybe UserTest)
insertUserIfNotPresent conn email =
  fmap listToMaybe .
  withDatabaseDebug putStrLn conn .
  Be.runInsertReturningList (_userTest testDb) $
  insertFrom . select $ do
    let
      mkUserLiteral = UserTest (val_ $ Auto Nothing) . val_
      user = mkUserLiteral email
    _ <- all_ (_userTest testDb) `union_` pure (mkUserLiteral "")
    guard_ (not_ (exists_ (filter_ (\u -> _userEmail u ==. val_ email) (all_ (_userTest testDb)))))
pure user
```

The generated SQL is

```sql
INSERT INTO "_user"("_userId", "_userEmail")
  SELECT DEFAULT AS "res0", 'andrew' AS "res1"
  FROM (
    (SELECT "t0"."_userId" AS "res0", "t0"."_userEmail" AS "res1" FROM "_user" AS "t0")
    UNION (SELECT DEFAULT AS "res0", '' AS "res1")
  ) AS "t0"
  WHERE NOT(EXISTS (
    SELECT "sub_t0"."_userId" AS "res0", "sub_t0"."_userEmail" AS "res1"
    FROM "_user" AS "sub_t0"
    WHERE ("sub_t0"."_userEmail") = ('andrew')
  ))
  RETURNING "_userId", "_userEmail"
```

I also have a [gist](https://gist.github.com/ajmccluskey/f0b5a6274d0c58e58a127ef51588ca19) with the complete example.

**Comment by tathougies** [comment]
Oh boy... Auto has really turned out to not be so great. I will have to do more digging to figure this one out.

**Comment by tathougies** [comment]
@ajmccluskey were you able to come up with a solution for your particular needs? Just FYI, I'm most likely going to remove `Auto` in the future and restrict usage of `default_` somehow.

**Comment by ajmccluskey** [comment]
@tathougies we did thanks. Was going to look at `ON CONFLICT`, but for now we're just running two queries to avoid duplicates.

**Comment by tathougies** [comment]
@ajmccluskey The issue with using Auto should now be fixed in master -- I've removed `Auto`, and the recommendation is to use `default_` on inserts instead. However, the current types allow you to put `DEFAULT` in arbitrary expressions, which is still wrong, but I've opened up #166 for that.
