### ISSUE TITLE
No implementation of lower(string) or upper(string) in Database.Beam.Query

### ISSUE THREAD

**Issue by gestone** [tathougies/beam#158]
Currently there's no implementation for `lower(string)` and `upper(string)`. I needed some way to test for case insensitivity and I wanted to use these functions in Beam.

As a work around, I decided to take the documentation's suggestion and used `customExpr_`:

```haskell
lower_ = customExpr_ (\text -> "LOWER(" <> text <> ")")
```

It'd be really nice if there were these functions built in.

**Comment by tathougies** [comment]
https://github.com/tathougies/beam/blob/355c2c3b5c5621498e65c3ede3d2353e197c1d92/beam-core/Database/Beam/Query/Combinators.hs#L332

**Comment by gestone** [comment]
Nice to see that it's implemented!

So how do I go about accessing that functionality? Looking at the .cabal file I see:

https://github.com/tathougies/beam/blob/355c2c3b5c5621498e65c3ede3d2353e197c1d92/beam-core/beam-core.cabal#L25

that `Database.Beam.Query.Combinators` isn't an exposed module.

**Comment by mulderr** [comment]
@gestone it's re-exported from `Database.Beam.Query` (or simply `Database.Beam`).

**Comment by gestone** [comment]
@mulderr So I should be able to do:

`import Database.Beam.Query (lower_)`

right?

Because I'm getting an error that says: `Module ‘Database.Beam’ does not export ‘lower_’`. Unless I'm doing something incorrectly?

**Comment by mulderr** [comment]
Yeah, that should work. Make sure you're using a recent commit. Both `lower_` and `upper_` were added fairly recently in https://github.com/tathougies/beam/commit/983f15a9bb95e74f152c39e891eb6a2b7be47ae6.
