### ISSUE TITLE
SELECT statement over nullable rows

### ISSUE THREAD

**Issue by sajidanower23** [tathougies/beam#160]
If I have a table defined like
```haskell
data UserT f = User
  { user_id         :: C f UUID
  , first_name      :: C f (Maybe Text)
  , phone_num       :: C f Text 
  } deriving Generic
```
And I want to find the user given `first_name` and `phone_num`. I have a function defined as:
```haskell
findUser :: Maybe Text -> Text -> Maybe UUID
findUser name phoneNum = do
  r <- withDatabaseDebug putStrLn $ runSelectReturningList $ select $ do
    user <- all_ (users myDb)
    guard_ (first_name user  ==. val_ name &&.
            phone user ==. val_ phoneNum
          )
    pure user
```
Note that `name` is a `Maybe Text` and within the function there is no way we can tell if it is a `Just n` or `Nothing`.

When `name` is Nothing, the generated SQL query is a more verbose variant of
```SQL
SELECT * from users where first_name = NULL AND phone = '1234';
```
Note that in SQL, you do not want to be doing a equality check for `NULL`. The expected generated SQL statement would be something like:
```SQL
SELECT * from users where first_name IS NULL AND phone = '1234';
```

Is it possible to special case for `SqlNull` and emit `IS` instead of `=`?

**Comment by tathougies** [comment]
Oh, this is really wrong, thanks for the report. I'll have to think about what the best solution is.
