### ISSUE TITLE
`runInsertReturningList` fails for Time

### ISSUE THREAD

**Issue by sajidanower23** [tathougies/beam#162]
`INSERT INTO .. RETURNING "some_time_val"` causes a parse error.

```haskell
data MyTimeT f = MyTime
  {
    my_time_id        :: C f UUID
  , my_time_val      :: C f LocalTime
  }
  deriving Generic
-- necessary instances defined here

generateTimeStamp :: IO LocalTime
generateTimeStamp = do
  nowish <- getCurrentTime
  return $ utcToLocalTime utc nowish

insertTime :: Connection -> IO ()
insertTime conn = do
  timeId <- nextRandom -- from Data.UUID.V4
  timeStamp <- generateTimeStamp

  withDatabaseDebug putStrLn conn $
        runInsertReturningList (_my_time myDb) $
               insertValues
               [
                 MyTime timeId timeStamp
               ]

```
When called, an SQL like the following is produced
```SQL
INSERT INTO "my_time"("my_time_id", "my_time_val") VALUES ('7f22c09c-965f-47b3-a2de-4063053588ab', '2018-03-08 01:36:54.045978')  RETURNING "my_time_id", "my_time_val"
```
And the exception is
```haskell
uncaught exception: PgError (PgRowParseError (RowCouldNotParseField 1))
```
The statement works fine when independently run in `psql`.

I have looked into this, and these are my findings:
- This only occurs for `runInsertReturningList`. It works fine for `insert`. This tells me that Beam can insert time properly but fails when trying to parse it back (because of the `RETURNING`)
- Tracing the function calls, the problem is possibly within the function [runPgRowReader](https://github.com/tathougies/beam/blob/master/beam-postgres/Database/Beam/Postgres/Connection.hs#L280)

I haven't looked deeply into `runPgRowReader` yet. If you could guide me a little, I am happy to open a PR.

**Comment by tathougies** [comment]
What's the type of the "my_time_val" column?

**Comment by sajidanower23** [comment]
It's `LocalTime`, imported from `Data.Time`.

**Comment by tathougies** [comment]
I meant, what's the type in the database?

**Comment by sajidanower23** [comment]
It's `timestamptz`.
That's what I use in migration.

**Comment by tathougies** [comment]
That's the issue then... `LocalTime` has no timezone information, whereas `timestamptz` does. You should use `ZonedTime` instead of `LocalTime`.

**Comment by sajidanower23** [comment]
Thanks. That was indeed the issue.
Does this definition make much sense then? Is there a reason anyone should use `timestamptz` in place of `timestamp`?
```haskell
timestamptz :: IsSql92DataTypeSyntax syntax => DataType syntax LocalTime
timestamptz = DataType (timestampType Nothing True)
```
Also, I could not find a migration type that returns `Datatype syntax ZonedTime`

**Comment by tathougies** [comment]
You're right, `timestamptz` should probably return `ZonedTime`. Let me look into this. Unless you have a suggestion as to what should work.

**Comment by sajidanower23** [comment]
I have tested it by making `timestamptz :: IsSql92DataTypeSyntax syntax => DataType syntax ZonedTime` and that works, and it makes sense, as far as I can see.

**Comment by sajidanower23** [comment]
@tathougies made a PR with the new migration type

**Comment by tathougies** [comment]
I decided to deserialize `LocalTime` from `timestamp with time zone` and `timestamp without time zone`. Would that work?

**Comment by sajidanower23** [comment]
Yep, that works! Thank you!

**Comment by lpsmith** [comment]
> I decided to deserialize `LocalTime` from `timestamp with time zone` and `timestamp without time zone`. Would that work?

The... unfortunate part of this decision is that reading a `LocalTime` from the database and then writing it back might not result in the same value,  because one `LocalTime` can at times correspond to two `UTCTime`s,  and the critical context is stripped out.   For example:

```
lpsmith=> set time zone 'America/New_York';
SET
lpsmith=> create temporary table foo (x timestamptz);
CREATE TABLE
lpsmith=> insert into foo values ('2019-11-03 05:30Z');
INSERT 0 1
lpsmith=> select * from foo;
           x            
------------------------
 2019-11-03 01:30:00-04
(1 row)
 
lpsmith=> select x::timestamp from foo;
          x          
---------------------
 2019-11-03 01:30:00
(1 row)
 
lpsmith=> insert into foo values ('2019-11-03 1:30');
INSERT 0 1
lpsmith=> select * from foo;
           x            
------------------------
 2019-11-03 01:30:00-04
 2019-11-03 01:30:00-05
(2 rows)
 
lpsmith=> select x at time zone 'utc' from foo;
      timezone      
---------------------
 2019-11-03 05:30:00
 2019-11-03 06:30:00
(2 rows)
```
