### ISSUE TITLE
Use of `maybeType` and `notNull` together in migration

### ISSUE THREAD

**Issue by sajidanower23** [tathougies/beam#177]
The beam snapshot I am using is `6a80a598073` (The last one pushed on 20 March).

I have noticed that in my migration function, it is possible to have a field like
```haskell
(field "my_row" (maybeType myType) notNull)
```
which says a row is both nullable and not-nullable, which doesn't make much sense, and causes a run-time exception when "my_row" is `Nothing`. Of course, writing something like this is a mistake from the part of the developer :stuck_out_tongue: .

I was wondering if it can be guaranteed at compile time that no-one does something like this? Would be more of an enhancement, I imagine.

**Comment by tathougies** [comment]
You're write that this is a very weird use! It should be possible to catch this at compile time. I will investigate!
