### ISSUE TITLE
First tutorial type errors on Database and autoDbSettings

### ISSUE THREAD

**Issue by Arguggi** [tathougies/beam#178]
Trying out Beam for the first time. The first tutorial won't compile, I think I fixed it with these changes:
```
data ShoppingCartDb f = ShoppingCartDb { _shoppingCartUsers :: f UserT }
  deriving Generic
```

should be 
```
data ShoppingCartDb f = ShoppingCartDb { _shoppingCartUsers :: f (TableEntity UserT) }
  deriving Generic
```

and  `autoDbSettings` should be `defaultDbSettings` . Am I correct?

**Comment by tathougies** [comment]
All the changes you mention are in the tutorial:

http://tathougies.github.io/beam/tutorials/tutorial1/

Sorry, what are you reading?

**Comment by Arguggi** [comment]
Ah, my bad, I was reading [this](http://travis.athougies.net/posts/2016-01-21-beam-tutorial-1.html) and [this](https://github.com/tathougies/beam/blob/master/Doc/01-BasicTutorial.lhs), didn't find the correct tutorial somehow.

Sorry for the noise, you can close this.

**Comment by tathougies** [comment]
Yeah, I actually should delete the ones in the repository... sorry for the confusion!
