### ISSUE TITLE
Make Columnar an open type family

### ISSUE THREAD

**Issue by Lysxia** [tathougies/beam#191]
Consider making `Columnar` an open type family that doesn't conflate type constructors with defunctionalized symbols.

The problem with the current closed type family is that, if `f` is a parameter, it is difficult to express the disequality constraints needed to restrict the context to the case where `Columnar f a = f a`.

That "default case" would need to be replaced with a wrapper

    data TyCon (f :: * -> *)
    type instance Columnar (TyCon f) a = f a

Although this suggestion adds noise to types (`User (TyCon Maybe)` instead of `User Maybe`), it makes generic programming more convenient for these records. For example, it is possible to derive instances like `Show`, `Monoid`, etc. for records indexed by `TyCon f` (in addition to `Identity`) with `f` as an adequately constrained parameter (`Show1`, `Alternative`, etc.) instead of only allowing fixed functor like `Maybe`.

**Comment by tathougies** [comment]
The two main purposes of the type family are to allow the Identity 'trick', and to make `Nullable` work with 'Identity', 'QExpr', or whatever else you stuff into the `f` parameter.

With that in mind, this proposal is long on work and short on details. If you make a branch, and demonstrate that this approach allows all current features to be supported *and* gets rid of code, I will gladly (actually really gladly!) consider adopting the approach and merging your branch.

There is one thing I want to address:

> For example, it is possible to derive instances like Show, Monoid, etc. for records indexed by TyCon f (in addition to Identity) with f as an adequately constrained parameter (Show1, Alternative, etc.) instead of only allowing fixed functor like Maybe.

The `Columnar` defunctionalization does not prevent you from deriving instances. What does is GHC's naive constraint generation in the `deriving` clause. You are free to use `StandaloneDeriving` with an appropriate instance head to derive all instances that GHC can derive:

```haskell
data MyTable f = MyTable { _column1 :: C f Blah, _column2 :: C f Bloop }
  deriving (Generic, Beamable)
deriving instance ( Show (C f Blah), Show (C f Bloop) ) => Show (MyTable f)
```

**Comment by Lysxia** [comment]
Thanks for the response. You make a good point about deriving instances. I was thinking of ways to use a more modular context `instance Show1 f => Show (MyTable f)`, or even replacing `Show1 f` with `forall a. Show a => Show (f a)`, but it's true that just keeping the context derived by GHC works well in many cases.

I don't have other good arguments for this suggestion, so I guess I can close the issue for now. I'll see if I can come up with a more concrete proposal.

**Comment by tathougies** [comment]
Please feel free to fork the code base and implement your proposal, if it cuts down on the bookkeeping we otherwise have to do, I really would happily merge it.

Thanks for taking the time to bring this up :)
