### ISSUE TITLE
Can't find module  Database.Beam.Backend.Sqlite3

### ISSUE THREAD

**Issue by jafonsor** [tathougies/beam#192]
Hi. I need some help with the tutorial.

In the tutorial here http://travis.athougies.net/posts/2016-01-21-beam-tutorial-1.html there is a module I can't find, neither on beam-core nor on beam-sqlite.

I'm using stack with solver lts-9.1 and added beam-core, beam-sqlite and text to the dependency list in the package.yaml.

**Comment by tathougies** [comment]
Those tutorials are obsolete (sorry!). If you've taken a look at the [README](https://github.com/tathougies/beam), there's a link to the new [user guide](https://tathougies.github.io/beam/), and the new [tutorials](https://tathougies.github.io/beam/tutorials/tutorial1/)

**Comment by jafonsor** [comment]
thanks

**Comment by jafonsor** [comment]
I am having trouble with the new one.

Here:
```
instance Database be ShoppingCartDb
```

I got this compile error:
```
• Expecting one fewer argument to ‘Database be’
      Expected kind ‘((* -> *) -> *) -> Constraint’,
        but ‘Database be’ has kind ‘Constraint’
• In the instance declaration for ‘Database be ShoppingCartDb’
```
