### ISSUE TITLE
Upgrading from 0.6 -> 0.7 trouble

### ISSUE THREAD

**Issue by boj** [tathougies/beam#215]
I was attempting to upgrade my code today, but ran into a problem I don't understand.

```
instance Database Postgres MyDb

queryAll :: Q PgSelectSyntax MyDb s (AssociationApplicationT (QExpr PgExpressionSyntax s))
queryAll = all_ (myDb ^. myAssociationApplication)

fetchAll :: MonadIO m
  => Connection
  -> m [AssociationApplicationReadable]
fetchAll conn = do
  vs <- liftIO $ withDatabase conn $
    runSelectReturningList $ select queryAll
  return . fmap toAssociationApplicationReadable $ vs
```

```
    • Couldn't match type ‘Database.Beam.Backend.SQL.SQL92.Sql92SelectSyntax
                             cmd0’
                     with ‘PgSelectSyntax’
      Expected type: SqlSelect
                       (Database.Beam.Backend.SQL.SQL92.Sql92SelectSyntax cmd0)
                       AssociationApplication
        Actual type: SqlSelect
                       PgSelectSyntax
                       (QExprToIdentity
                          (AssociationApplicationT
                             (QExpr PgExpressionSyntax Database.Beam.Query.QueryInaccessible)))
      The type variable ‘cmd0’ is ambiguous
    • In the second argument of ‘($)’, namely ‘select queryAll’
      In the second argument of ‘($)’, namely
        ‘runSelectReturningList $ select queryAll’
      In the second argument of ‘($)’, namely
        ‘withDatabase conn $ runSelectReturningList $ select queryAll’
```

What am I missing?

**Comment by tathougies** [comment]
The functional dependencies on `MonadBeam` were relaxed to allow us to potentially allow `MonadBeam` over monad transformers. However, this means we can't tell what the command syntax is from just the connection handle, which we could in the past. The best way to get around this is to use the `runBeamPostgres` and `runBeamSqlite` functions for `beam-postgres` and `beam-sqlite`. If you're doing backend-generic stuff, then an explicit type annotation on just the monad should suffice.

There's some work in #200 that will reintroduce the functional dependencies in a different way, but I haven't had time to review it yet.

Sorry for the inconvenience!

**Comment by boj** [comment]
Thanks, I completely missed that. Added a PR to fix a couple minor things.
