### ISSUE TITLE
Haddocks for `IsBeamSerialColumnSchemaSyntax` incorrect?

### ISSUE THREAD

**Issue by ajmccluskey** [tathougies/beam#219]
The docs for `IsBeamSerialColumnSchemaSyntax` might have an error. The usage example says it can be used for auto-incrementing values in migrations like so.

```haskell
field "Key" int genericSerial
```
However, `genericSerial` has the following type:

```haskell
genericSerial :: FieldReturnType 'True 'False syntax (SqlSerial Int) a => Text -> a
```
Should the example be `genericSerial "Key"`?

See https://github.com/tathougies/beam/blob/master/beam-migrate/Database/Beam/Migrate/SQL/BeamExtensions.hs#L19

**Comment by tathougies** [comment]
Yes, it's wrong... good catch. I'll fix it later today.

**Comment by tathougies** [comment]
Fixed in master.
