### ISSUE TITLE
[Docs] SQL tab is empty in the tutorial

### ISSUE THREAD

**Issue by MaxGabriel** [tathougies/beam#226]
In the "Querying the Database" section of the [tutorial](https://tathougies.github.io/beam/tutorials/tutorial1/), the example code has 3 tabs, one each for Haskell, SQL, and Haskell output.

The SQL one is blank though. I'm not sure if this is is expected, but it looks like the SQL is included in the Output tab.

![image](https://user-images.githubusercontent.com/1274145/39411533-cd0efaf6-4bc0-11e8-9106-8b0d12370fcb.png)

I'm viewing the page in Chrome 66.0.3359.139 on MacOS

Btw: the tabbed Haskell/SQL/Output is a great idea

**Comment by tathougies** [comment]
Thanks for the report! Will fix very soon :)

**Comment by MaxGabriel** [comment]
Cool talk at BayHac :)

**Comment by tathougies** [comment]
Thank you very much! This is all fixed now :)
