### ISSUE TITLE
How to override default field naming rules

### ISSUE THREAD

**Issue by mulderr** [tathougies/beam#237]
Currently using something like:

```haskell
defaultDbSettings
  `withDbModification`
  dbModification
    { _dbBlogPost = modifyTable id $ tableModification { ... } }
```
to set each field name individually.

Ideally I'd rather override the default name generation rules if possible. Instead of strip the first word I'd like to strip the name of the constructor. Ex:

```haskell
data BlogPostT f
  = BlogPost
    { _blogPostId :: Columnar f Int64
    , _blogPostText :: Columnar f Text
    } deriving Generic
```

Should generate columns named `id` and `text` instead of `post_id` and `post_text`.

Is there a way to do that? Looking at code in [Tables.hs](https://github.com/tathougies/beam/blob/master/beam-core/Database/Beam/Schema/Tables.hs) but I'm totally lost.

**Comment by 3noch** [comment]
Dup #89

**Comment by mulderr** [comment]
Ah, there's even examples! Thanks, my bad for not checking properly.
