### ISSUE TITLE
AUTO_INCREMENT in the sqlite3 tutorial

### ISSUE THREAD

**Issue by coot** [tathougies/beam#238]
The tutorial (in part 2) has this sqlite3 schema for addresses table:
```
CREATE TABLE addresses ( id INT AUTO_INCREMENT PRIMARY KEY, address1 VARCHAR NOT NULL, address2 VARCHAR, city VARCHAR NOT NULL, state VARCHAR NOT NULL, zip VARCHAR NOT NULL, for_user__email VARCHAR NOT NULL );
```

But this does not insert the default values into the primary key (at least as of sqlite3 version `3.23.1 2018-04-10 17:39:29 4bb2294022060e61de7da5c227a69ccd846ba330e31626ebcd59a94efd14alt2`).  This works instead:

```
CREATE TABLE addresses ( id INTEGER PRIMARY KEY, address1 VARCHAR NOT NULL, address2 VARCHAR, city VARCHAR NOT NULL, state VARCHAR NOT NULL, zip VARCHAR NOT NULL, for_user__email VARCHAR NOT NULL );
```

Link to [sqlite3 docs](http://www.sqlite.org/autoinc.html).

**Comment by tathougies** [comment]
Thanks for the report. Merged your PR.

**Comment by antislava** [comment]
Encountered this error yesterday (SQLite version 3.26.0 2018-12-01). The old SQL table creation command is still used in the tutorial (http://tathougies.github.io/beam/tutorials/tutorial2/): 
```
sqlite> CREATE TABLE addresses ( id INT AUTO_INCREMENT PRIMARY KEY, address1 VARCHAR NOT NULL, address2 VARCHAR, city VARCHAR NOT NULL, state VARCHAR NOT NULL, zip VARCHAR NOT NULL, for_user__email VARCHAR NOT NULL );
```
