### ISSUE TITLE
beam-migrate-cli is unabailable on Hackage

### ISSUE THREAD

**Issue by Znack** [tathougies/beam#249]
Hi! I'm trying to play with Beam, it looks as very attractive library to handle databases in real-world apps :)
Although I could not find `beam-migrate-cli` tool nowhere, the link from documentation of `beam-migrate` that leads to `beam-migrate-cli` now is broken: http://hackage.haskell.org/package/beam-migrate-cli

Thank you

**Comment by mulderr** [comment]
Hello! AFAIK, beam-migrate-cli is very much a work in progress. In the meantime you can try to tap into beam-migrate functionality directly. See [here](https://github.com/tathougies/beam/issues/242) for a very basic example of creating a schema from scratch. You may also be interested in `verifySchema` and `autoMigrate` from `Database.Beam.Migrate.Simple` - you should be able to use those in the same fashion.

**Comment by Znack** [comment]
I've just managed to clone and build Beam repository locally, added the folder with project's executables to the Path and everything is working with a cli interface now :)

Thank you a lot for pointing out to that issue, somehow I've skipped it while looking through information about the migrations.
