### ISSUE TITLE
Cannot select addresses in Tutorial Part2: ConversionFailed

### ISSUE THREAD

**Issue by nlv** [tathougies/beam#250]
I try do  part2 of tutorial, But stuck in 

```
                   addresses'' <- runSelectReturningList $ select (all_ (shoppingCartDb ^. shoppingCartUserAddresses))
                   liftIO $ mapM_ print addresses''

```

In runtime I got error:

> 
> SELECT "t0"."id" AS "res0", "t0"."address1" AS "res1", "t0"."address2" AS "res2", "t0"."city" AS "res3", "t0"."state" AS "res4", "t0"."zip" AS "res5", "t0"."for_user__email" AS "res6" FROM "addresses" AS "t0";
> -- With values: []
> simple-exe: ConversionFailed {errSQLType = "NULL", errHaskellType = "Int", errMessage = "need an int"}
> 

Working example: [https://github.com/nlv/haskell_beam_test/blob/lens-failure/src/Lib.hs#L166](https://github.com/nlv/haskell_beam_test/blob/lens-failure/src/Lib.hs#L166).

**Comment by nlv** [comment]
The problem was in using primary key in addresses table;

> CREATE TABLE addresses ( id INT AUTO_INCREMENT PRIMARY KEY, address1 VARCHAR NOT NULL, address2 VARCHAR, city VARCHAR NOT NULL, state VARCHAR NOT NULL, zip VARCHAR NOT NULL, for_user__email VARCHAR NOT NULL );

doesn't work in my case. Field id is not autocrement when inserting row to addresses table. 
And id field was NULL!

I've created addresses with:

> CREATE TABLE addresses ( id INTEGER PRIMARY KEY  AUTOINCREMENT, address1 VARCHAR NOT NULL, address2 VARCHAR, city VARCHAR NOT NULL, state VARCHAR NOT NULL, zip VARCHAR NOT NULL, for_user__email VARCHAR NOT NULL );

And all is OK!

I thing it is becouse I use sqlite3:

> nlv@nlv-TM1701:~/WORK/haskell/beam$ sqlite3 --version 
> 3.19.3 2017-06-08 14:26:16 ...

There may be two options for creating tables in the documentation: 1) for sqllite2 and 2) for sqllite3?

**Comment by tathougies** [comment]
The syntax for AUTOINCREMENT may need to be updated in the docs. submit a PR if you feel up to it; otherwise, I'll get to it :)

**Comment by nlv** [comment]
Ok

**Comment by nlv** [comment]
It'seems autoincriment had been fixed 4 days ago: https://github.com/tathougies/beam/commit/4b1fdd7680600183a4c6fd58929492779eb27487
:)
