### ISSUE TITLE
Good place to ask newbie questions?

### ISSUE THREAD

**Issue by saurabhnanda** [tathougies/beam#254]
Is this issue tracker a good place to ask newbie questions? Any tag on Stackoverflow that the community/maintainers check? Any Google group?

**Comment by tathougies** [comment]
There's a google group, linked in the README: https://groups.google.com/forum/#!forum/beam-discussion

I'm also in IRC during the week during working hours Pacific Standard Time.

**Comment by saurabhnanda** [comment]
@tathougies thanks!
