### ISSUE TITLE
Custom types in columns

### ISSUE THREAD

**Issue by kmicklas** [tathougies/beam#262]
The ability to abstract across database backends in Beam (in my case Postgres and SQLite) is pretty awesome but I've noticed it's easy to get stuck in a lowest-common-denominator situation. Specifically writing schemas which will work on SQLite requires using `TEXT` or `BLOB` for a lot of types that would have real representations in Postgres (e.g. `UUID`, Aeson `Value`, etc.).

I'd like to be able to write something like

```
instance BackendType Sqlite MyType Text where
  toBackendType = decodeUtf8 . encode
  fromBackendType = decode . encodeUtf8

insance BackendType Postgres MyType Value where
  toBackendType = toJSON
  fromBackendType = resultToMaybe . fromJSON
```

and then use `MyType` in a Beam column and have all the appropriate instances. Besides the additional backend abstraction, this also has the benefit of making the table types more suitable for passing around in the application since domain-specific types can be used.

**Comment by tathougies** [comment]
You can certainly already do this! Basically, just create a newtype wrapper. Then instantiate `HasDefaultSqlDataType`, `HasDefaultSqlDataTypeConstraints`, `FromBackendRow` and `HasSqlValueSyntax`. Just unwrap/wrap the newtype where appropriate.

**Comment by kmicklas** [comment]
Cool, I didn't realize this was already possible. Would you support a more streamlined way to do this using just one class? I'm happy to implement it if you think it's a good idea.

**Comment by tathougies** [comment]
The `HasDefault...` classes are from `beam-migrate`, while the other two are from `beam-core`. I'm planning on combining the `beam-migrate` classes in the beam-0.8.0.0 branch. The other two classes (`FromBackendRow` and `HasSqlValueSyntax`) can't quite be combined, because `FromBackendRow` has instances for tuples of types which also satisfy `FromBackendRow`, while `HasSqlValueSyntax` does not. You do not need to provide any implementation of `FromBackendRow` if you provide an appropriate backend-specific instance (`Database.PostgreSQL.Simple.FromField` for `beam-postgres`). Haskell's open world assumption means we have to manually instantiate the class, but can leave it blank.

**Comment by kmicklas** [comment]
I don't mean combining them into one class, but rather providing one class which the user can implement to piggyback off the instances for standard SQL types provided by the backend via a bidirectional conversion. As far as I know the classes you mentioned aren't sufficient for that; you would need `HasSqlEqualityCheck`, etc. In addition you would need to produce some backend-specific data (e.g. `SqliteValueSyntax`) which might not even be exposed.

**Comment by tathougies** [comment]
All syntaxes should be exposed if you import the `Database.Beam.*.Syntax` modules. Can you provide an example of how you think it should work? I don't understand what you mean when you say 'one class which the user can implement to piggyback off the instances for standard SQL types'. More clearly, I think I understand that you want a syntactically short way of instantiating all type classes, but I don't think Haskell has this ability.

**Comment by kmicklas** [comment]
My original comment has an example of how I think the class might be instantiated. The signature would be something like

```
class BackendType be a b | a -> b where
  toBackendType :: a -> b
  fromBackendType :: b -> a
```

Then for example the SQLite backend would have instances like

```
instance (BackendType Sqlite a b, FromBackendRow Sqlite b) => FromBackendRow Sqlite a where
  ...
```

(for `FromBackendRow` and all the other classes a column type might instantiate) using `toBackendType` and `fromBackendType` as appropriate.

Then if you define a `BackendType` instance for some custom type, you would get exactly the set of instances that the underlying backend type has.

**Comment by tathougies** [comment]
Oh I see what you want. The issue here is Haskell, not my willingness to do that. Your open `FromBackendRow Sqlite a` instance would overlap with what we already have.

**Comment by kmicklas** [comment]
Ugh, I always forget that instance resolution doesn't backtrack like this, even though (I think) the orphan rules should make it possible. :frowning_face:

**Comment by Ericson2314** [comment]
```haskell
newtype BeamPerBackendIso be b a = BeamPerBackendIso { be :: ExistingBackendType }
instance (BackendType be a b, FromBackendRow Sqlite b) => FromBackendRow be (ExistingBackendType be b a) where
  ...
```
Should be just fine as GHC 8.6 "deriving via" strategy.

**Comment by mrehayden1** [comment]
For anyone else landing here looking for more explanation: https://groups.google.com/forum/m/#!topic/beam-discussion/vhasiYgd26E

**Comment by cumber** [comment]
It would be *really* good to have an example of this in the tutorial. Just something as simple as explaining how to use `newtype Email = Email Text` to keep email addresses distinct from other texts in Haskell-land, but storing as text column in the database.

**Comment by xaviershay** [comment]
For my future self, here are a couple of examples of using custom types that, while appearing straightforward now took me a while to figure out. Still not convinced I totally understand the `fromBackendRow` monad or how that composes but they _appear_ to be working.

```
-- Newtype wrapper around a text column
newtype GameId = GameId Text

instance FromBackendRow Postgres GameId where
  fromBackendRow = GameId <$> fromBackendRow

instance HasSqlValueSyntax be Text => HasSqlValueSyntax be GameId where
  sqlValueSyntax (GameId x) = sqlValueSyntax x

-- Game has a ToJSON instance, but we want to reuse the PgJSONB type from beam-postgres rather than encode to bytestring ourselves.
instance FromBackendRow Postgres Game where
  fromBackendRow = (\(PgJSONB g) -> g) <$> fromBackendRow

instance HasSqlValueSyntax be (PgJSONB Game) => HasSqlValueSyntax be Game where
  sqlValueSyntax x = sqlValueSyntax (PgJSONB x)
```
