### ISSUE TITLE
Support for ROW_NUMBER?

### ISSUE THREAD

**Issue by dsvensson** [tathougies/beam#265]
~~select distinct on seems to be missing. The nub_ function works as regular distinct~~. Trying to accomplish selecting the first entry per group of data, similar to what's described here:

https://www.periscopedata.com/blog/first-row-per-group-5x-faster

Which brings up the other missing part, ROW_NUMBER().

Am I simply missing something, and these are available in some other way?

**Comment by dsvensson** [comment]
...found pgNubBy_, so question is probably more wrt ROW_NUMBER.

**Comment by tathougies** [comment]
For now you can use `customExpr_` as described [here](http://tathougies.github.io/beam/user-guide/extensibility/)

**Comment by tathougies** [comment]
Fixed in 89822404838cc510dcf8046d1bf9cb7dec884a25
