### ISSUE TITLE
Beam-migrate schema generation from database

### ISSUE THREAD

**Issue by tathougies** [tathougies/beam#27]
Given a database, we should be able to generate a reasonable enough schema for it. We can likely use the current diffing code.

**Comment by SamuraiJack** [comment]
Is this issue still open? I thought its already impelemented?
From the web site: 
>>Easy schema generation from existing databases

**Comment by tathougies** [comment]
From [the docs](http://tathougies.github.io/beam/schema-guide/migrations/)

> The beam-migrations package is still a WIP. The following manual represents both planned and implemented features. If you'd like to help guide development, please join the beam-discussion mailing list.

I'll note it on the main page, sorry. I am working on it right now, but it's actually not straightforward :)

**Comment by tathougies** [comment]
@SamuraiJack The [nextgen-beam-migrate](https://github.com/tathougies/beam/tree/travis/nextgen-beam-migrate) branch has a `beam-migrate` tool that will help you generate (simple) schemas from backends that support it. Currently, only postgres is supported, but I'm working on sqlite.

To invoke

```
$ stack exec -- beam-migrate simple schema --backend Database.Beam.Postgres.Migrate --connection "postgres connection string"
```

If you're using cabal, you may have to explicitly set the ghc package path to point to the cabal sandbox or wherever `beam-postgres` is installed.

```
$ beam-migrate --package-path path/to/ghc-package-conf simple schema --backend Database.Beam.Postgres.Migrate --connection "pg connection string"
```

**Comment by SamuraiJack** [comment]
What the "simple" does mean? Some features not implemented yet?

Am I correct that it will generate source files with DB schema definition (in Haskell)?

**Comment by tathougies** [comment]
@SamuraiJack  the `beam-migrate` command is meant to expose an entire system for handling migrations. When complete, it will manage your haskell schema and backend databases and handle deployment on staging and production as well as local testing. I'm planning on making it quite opinionated.

However, I don't want to force people to use it. The `simple` subcommand exposes non-stateful operations, such as extracting a Haskell schema from a database, or (in the future) calculating a sql migration script between two beam schemas. If you run the command, it will output a haskell module to stdout that will contain a correct haskell data type for each table, a `Table` instance, a database type for the entire database, and a value of that type that can be used to access the individual tables. The module exports two symbols `db` and `migration`. `db` can be used in queries, `migration` can be used to create the schema in an empty database.

**Comment by SamuraiJack** [comment]
Sounds cool. 

I'll give it a try soon.

**Comment by SamuraiJack** [comment]
It worked, schema module has been generated just fine. It required TypeApplications extension to compile though (not listed at the top). 

I'll try to create some queries now..

**Comment by SamuraiJack** [comment]
Would be cool to insert some kind of separators between the table definitions in the generated schema module - to easier understand the structure of file.
