### ISSUE TITLE
MonadBeamInsertReturning and friends still have restrictive fun deps

### ISSUE THREAD

**Issue by ocharles** [tathougies/beam#273]
`MonadBeam` is now just `MonadBeam syntax be handle m | m -> syntax be handle`, but:

* `MonadBeamInsertReturning syntax be handle m | m -> syntax be handle, be -> m, handle -> m`
* `MonadBeamUpdateReturning syntax be handle m | m -> syntax be handle, be -> m, handle -> m`
* `MonadBeamDeleteReturning syntax be handle m | m -> syntax be handle, be -> m, handle -> m`

Could these be weakened in the same way?

**Comment by tathougies** [comment]
This is fixed in the `beam-0.8.0.0` branch which I plan on releasing soon. Should be usable with monad transformers.

**Comment by ocharles** [comment]
Great, thanks!
