### ISSUE TITLE
VARCHAR drops size when verifying schema (postgres)

### ISSUE THREAD

**Issue by dbaynard** [tathougies/beam#274]
The `autoMigrate` function was throwing errors, and I managed to isolate the cause — `verifySchema` returned the following error:

```
VerificationFailed [(TableHasColumn PgColumnSchemaSyntax: Table "punts" must have a column "user" of VARCHAR(6))]
```

Viewing the constraints with `backendGetDbConstraints migrationBackend` gave the following:

```
TableHasColumn PgColumnSchemaSyntax: Table "punts" must have a column "user" of VARCHAR
```

The difference is the `(6)`.

The corresponding instance is below

```haskell
instance HasDefaultSqlDataType PgDataTypeSyntax UserId where
  defaultSqlDataType _ _ = varCharType (Just 6) Nothing
instance IsSql92ColumnSchemaSyntax c => HasDefaultSqlDataTypeConstraints c UserId
```

Switching to `varCharType Nothing Nothing` or `pgTextType` resolved the issue — but I'd wanted the schema to restrict the data.

**Comment by tathougies** [comment]
Fixed in beam-0.8.0.0 in the above commit.
