### ISSUE TITLE
Postgres does not get auto increment functionality for beam-migrate

### ISSUE THREAD

**Issue by Fresheyeball** [tathougies/beam#277]
A primary key int does not automatically get a seq.

**Comment by dbaynard** [comment]
You probably want [serial](https://hackage.haskell.org/package/beam-postgres-0.3.2.2/docs/Database-Beam-Postgres-Migrate.html#v:serial)?

**Comment by rsoeldner** [comment]
I encountered this issue too. I'm using the `autoMigrate` functionality. How can I enforce mapping `Int` to `serial` ? 

Example structure:
```
   data DocumentT f
    = Document
    { documentId        :: C f Int
    , documentName      :: C f Text
    } deriving Generic
```

**Comment by kmicklas** [comment]
@rsoeldner You need `SqlSerial` for the type definition.
