### ISSUE TITLE
'\NUL' within Json produces error.

### ISSUE THREAD

**Issue by vwwv** [tathougies/beam#297]
When using `PgJSONB` or `PgJSON`, if the json object contains the string "\u000", it will fail to insert it into the database. Example:

```
data Foo = Foo{ foo :: Text} deriving (ToJSON, FromJSON...)

data TableT f = Table{ _column :: C f Foo } deriving(Generic,Beamable ...)

instance Table TableT where ....

data DB = ....

db ::  = DatabaseSettings  Postgres DB
db = ....

hereItFails = runInsert . insert ( _table db) $ insertValues [ Foo "\NUL" ]
```

Notice that `encodeJSON "\NUL" == "\"\\u000\"" `

**Comment by tathougies** [comment]
Added test for this in https://github.com/tathougies/beam/commit/02a502fd4ca012cad8bbb161aab7aa494d596ece and things seem to be working now.
