### ISSUE TITLE
Different resolvers for different stack.yaml

### ISSUE THREAD

**Issue by alexfmpe** [tathougies/beam#298]
I tried to run `stack --nix` inside `beam-core` and was surprised to see it attempting to download a ghc given that I had already built the top-level project some days ago. 

This is caused by the sub-packages having an older resolver. Is this intended?

https://github.com/tathougies/beam/blob/master/stack.yaml#L3
vs 
https://github.com/tathougies/beam/blob/master/beam-core/stack.yaml#L5

**Comment by tathougies** [comment]
No it is not intended. I've removed them in master and beam-0.8.0.0
