### ISSUE TITLE
add domain types

### ISSUE THREAD

**Issue by echatav** [tathougies/beam#311]
Add `CREATE DOMAIN` statements. [documentation](https://www.postgresql.org/docs/current/static/sql-createdomain.html). Something like...

```Haskell
createDomain
  :: Alias domain
  -> ColumnExpression schema (def :=> ty)
  -> (forall table. TableConstraint schema table constraint)
  -> Definition schema (Create alias ('Typedef ty) schema)
```

I'd need some sort of Haskell constraint or type-proof to link `domain` with the `constraint`; that is, the latter should be constrained to `'Check '[domain]`, `'Unique '[domain]`, etc.

**Comment by echatav** [comment]
Shit, sorry @tathougies , major faux pas! Meant to open it up on my own repo but really I think Beam is amazing! I've been reading your code and tutorials and had these issues open in a tab.

**Comment by tathougies** [comment]
Haha... all github repositories look the same to me too! For the record, domain types are something I'd like to support with 0.8.0.0. Good work on squeal. I saw the 0.4 announcement. Looks very nice!

**Comment by echatav** [comment]
We should do a comparison talk at a Bay Area Haskell meetup some time. I'd love to get some ideas from you!
