### ISSUE TITLE
beam-core ghc-8.6.1 errors

### ISSUE THREAD

**Issue by antislava** [tathougies/beam#315]
Errors:
  1) Version constraint on containers
  2) Need to explicitly add `UndecidableInstances` in `beam-core/Database/Beam/Schema/Lenses.hs`
Fix: https://github.com/antislava/beam/commit/c6e1e43fbbf2d30f3cc8f29ac3dec5846c1507ac

**Comment by tathougies** [comment]
Please open a PR. Thank you for the contribution.

**Comment by endgame** [comment]
I'm confused. I've just hit these problems, but the fix has in master, but the cabal file says its [0.7.2.1](https://github.com/tathougies/beam/blob/2489a213cdee6341de46a3aa015c35067f4d6076/beam-core/beam-core.cabal#L5) while the latest version on hackage is 0.7.2.2 and doesn't have the relaxed dependencies. What am I missing?

**Comment by tathougies** [comment]
Hmm... perhaps a merge overwrote the version number. I'll update and upload to hackage as 0.7.2.3.

**Comment by endgame** [comment]
The funky version numbers seem to affect other packages too: beam-migrate-0.3.2.1 exists on hackage but the cabal file on master says 0.3.2.0. An errant merge might be the cause, and require pushing other packages in this project.

**Comment by endgame** [comment]
beam-postgres is similarly affected; probably worth doing a full round of releases.

**Comment by peti** [comment]
Ping?

**Comment by peti** [comment]
@tathougies, will you release a version of `beam` that works with ghc-8.6.x?

**Comment by tathougies** [comment]
Just compiled master on stackage latest lts (13.6) with GHC 8.6.3. I'm uploading new 0.7 releases to hackage now.
