### ISSUE TITLE
Support for VALUES expressions

### ISSUE THREAD

**Issue by bgamari** [tathougies/beam#325]
It would be nice to be able to use a list of Haskell values in a query as an SQL `VALUES` expression. For instance,
```haskell
values_ :: [a] -> Q select db s a

-- For instance...
data DocumentName

missingDocuments :: [DocumentName] -> Q select db DocumentName -> Q select db DocumentName
missingDocuments d d' = values_ d `except_` d'
```

I would expect `missingDocuments ["doc1", "doc2", "doc3"] (all_ (db ^. documents))` to produce something like the following SQL92
```sql
VALUES ('doc1'), ('doc2'), ('doc3') EXCEPT (SELECT documentName FROM documents)
```

**Comment by tathougies** [comment]
Way ahead of you: https://github.com/tathougies/beam/blob/travis/beam-0.8.0.0/beam-core/Database/Beam/Query/Combinators.hs

Been there for a few months now :)

Will be making a 0.8.0.0 release on hackage/stackage soon. Just need to work through some bugs and finish up schema support.
