### ISSUE TITLE
Non-compiling example of tables without primary keys

### ISSUE THREAD

**Issue by adetokunbo** [tathougies/beam#328]
The documentation provides [an example](https://tathougies.github.io/beam/user-guide/models/#what-about-tables-without-primary-keys) for how to model tables that don't have primary keys.
It does not compile under beam-core-0.7.2.2

```haskell
data BadT f
  = BadT
  { badFirstName :: C f Text
  , badLastName  :: C f Text
  } deriving Generic
instance Beamable BadT
instance Table BadT where
  data PrimaryKey BadT f = BadNoId
  primaryKey _ = BadNoId
```

```haskell
 error:
    • No instance for (Beamable (PrimaryKey BadT))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Table BadT’
   |
71 | instance Table BadT where
   |          ^^^^^^^^^^
```

**Comment by tathougies** [comment]
You still need to do `derive Generic` on the PrimaryKey and then do `instance Beamable (PrimaryKeyT BadT)` just as you would with a normal primary key.

I've added a new test to verify that this works. See [here](https://github.com/tathougies/beam/blob/8503c45e118d911b5d158d23f9b25fcc0f3acb37/beam-core/test/Database/Beam/Test/Schema.hs#L287)

**Comment by adetokunbo** [comment]
Thanks for responding so quickly!

**Comment by adetokunbo** [comment]
Just sent you #330 which updates the example in docs
