### ISSUE TITLE
Foreign key column name incorrect

### ISSUE THREAD

**Issue by karls** [tathougies/beam#33]
Hi @tathougies!

I'm investigating using Beam in our project. While having a play around with it, I came across a behaviour where by using `oneToMany_` generates the foreign key name incorrectly — it seems to append `__id` no matter what I do.

I've defined my foreign key as `interviewCandidateId :: PrimaryKey CandidateT f` and a helper function like so:

```
candidateInterviews :: OneToMany AppDb s CandidateT InterviewT
candidateInterviews =
  oneToMany_ (interviews appDb) interviewCandidateId
```
Which results in an error saying something like this:

```
Exception: Postgres error: Just "ERROR:  column t0.candidate_id__id does not exist\nLINE 1: SELECT \"t0\".\"id\" AS \"res0\", \"t0\".\"candidate_id__id\" AS \"res1..
```

Am I just _doing it wrong_ ™? Is there something I'm missing? I've tried both the `travis/beam-0500` branch as well as `master`.

**Comment by tathougies** [comment]
@karls 
I believe this is expected behavior. If you want to rename the foreign key column name, you can use the [method described here](http://tathougies.github.io/beam/user-guide/databases/#modifying-the-defaults) to rename the primary key column.

**Comment by karls** [comment]
Hey, thanks for the clarification and the suggestion! I tried to modify the foreign key field name, but it does not seem to be possible? According to https://github.com/tathougies/beam/blob/master/beam-core/Database/Beam/Schema/Tables.hs#L132 field modifications only work on `Columnar`-s?

**Comment by tathougies** [comment]
Indeed, you can only rename a `Columnar`, but an embedded primary key is composed of columnars.

In [the Chinook schema](https://github.com/tathougies/beam/blob/master/beam-sqlite/examples/Chinook/Schema.hs), we rename all the columns, including foreign keys embedded in other tables. We use the `IsString` instance of `FieldModification`.

So basically (making it very explicit) if you have

```
data CustomerT f
  = Customer
  { customerId        :: Columnar f Int32
  , customerFirstName :: Columnar f Text
  , customerLastName  :: Columnar f Text
...
  } deriving Generic
instance Beamable CustomerT
type Customer = CustomerT Identity; deriving instance Show Customer

instance Table CustomerT where
  data PrimaryKey CustomerT f = CustomerId (Columnar f Int32)


data InvoiceT f
  = Invoice
  { invoiceId       :: Columnar f Int32
  , invoiceCustomer :: PrimaryKey CustomerT f
...
  } deriving Generic
```

Then you can do

```
  defaultDbSettings `withDbModification`
  (dbModification
   { ...
   , invoice = modifyTable (\_ -> "Invoice")
                   (tableModification { invoiceCustomer = CustomerId (fieldNamed "CustomerId") })
    })
```

**Comment by karls** [comment]
Oh! Thanks for spelling this out for me — I got my example working as well now.

There is a fair number of types jiggle around and learn how they all fit together, but I'm hopeful. I will continue to evaluate beam for our project. :-)

Btw, appending pattern of appending `__id` — I hadn't come across it before.

**Comment by tathougies** [comment]
Awesome! Feel free to ask any more questions on the discussion list. 

> Btw, appending pattern of appending __id — I hadn't come across it before.

Just an easy way of generating unique column names :)

**Comment by wraithm** [comment]
@tathougies This should definitely be documented better. It took me a second to figure out what's going on with foreign key field names.
