### ISSUE TITLE
Use with dependent typing features

### ISSUE THREAD

**Issue by CaptJakk** [tathougies/beam#350]
This is a potentially impossible feature request but we are currently trying to implement database models that are parameterized by another type besides the `f` variable typically present. Like this:

```haskell
data ModelT (p :: SingletonIndexType) f = Model
  { field1 :: C f UUID
  , field2 :: C f (SingletonAlias p)
  } deriving (Generic)
```
This is all well and good and in fact works but heres the trouble. I'd like to be able to merge all of these indexed datatypes into the same table. I.E.

```haskell
data MyDb f = MyDb
  { _myDbModels :: f (TableEntity ModelT p) -- <- p is not currently in scope
  } deriving (Generic) -- <- existentials prevent Generic derivations
```
Here's the rub, If I universally quantify over p and move it into a type variable on the database itself, I now (in essence) have my entire database indexed over p, which is not something I really want. On the other hand, if I redefine `MyDb` to existentially quantify over p, then Generic instances can no longer be derived.

My initial instinct at this point is to hand define instances of Database/Table/Beamable etc. rather than using the default Generics based ones. However, literally EVERY piece of documentation in the library says not to do this.

So here's the question: Is what I'm attempting to do even possible/sane? If so, is this a temporary or fundamental limitation of beam? If not, why not?

**Comment by tathougies** [comment]
The documentation says not to define Database/Table/Beamable instances because it's not necessary in the cases in the documentation. If you're going to extend the library, then you may need to make provisions for doing this.

To answer your questions:

> This is a potentially impossible feature request but we are currently trying to implement database models that are parameterized by another type besides the `f` variable typically present.

This is totally possible, supported, and used in production.

> This is all well and good and in fact works but heres the trouble. I'd like to be able to merge all of these indexed datatypes into the same table. I.E.

Again, totally fine. You'll need to add some constraints to your database value, but that's fine.

> On the other hand, if I redefine `MyDb` to existentially quantify over p, then Generic instances can no longer be derived.

That's correct. You'll be stuck writing instances by hand, or using Template Haskell.

**Comment by CaptJakk** [comment]
Understood. Just wanted to make sure I was understanding the process correctly. Thank you for your time and effort with this!
