### ISSUE TITLE
Support for PostgreSQL regular expressions

### ISSUE THREAD

**Issue by ocharles** [tathougies/beam#355]
As far as I can tell, `beam-postgres` doesn't support PostgreSQL regular expressions: https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP. It would be great to have at least a subset of this functionality, like the `~*` operator.

**Comment by tathougies** [comment]
Fixed in latest master: a89da5ba70f1e10b907097548a02ff6dd08e192d
