### ISSUE TITLE
How to create a simple delete all rows query (documentation please)?

### ISSUE THREAD

**Issue by oderwat** [tathougies/beam#370]
While playing with Beam I was originally looking for "truncated table" support but then found it as not yet supported in the todo section.

So I wanted to create a simple "delete all rows query" for the time being but miserably failed the task. I could not find out how to create such query. I am now using an ugly work around:

```Haskell
deleteUsers conn = runBeamMySQL conn $ runDelete $
  delete (_blogUsers blogDb) (\c -> _userId c /=. 0)
```

What is the right way to do it? Maybe there could be an example added to the documentation.

From the documentation I would have expected that it works like this:

```Haskell
deleteArticles conn = runBeamMySQL conn $ runDelete $
  delete (all_ (_blogArticles blogDb))
```

**Comment by 3noch** [comment]
You should be able to replace `(\c -> _userId c /=. 0)` with `(const $ val_ True)` as a not-so-ugly workaround.

**Comment by oderwat** [comment]
Yes. Thank you that works. For some reason I was missing the `const` while trying it myself. I still think that there could be an example in the documentation. I don't think using this constant expression is too bad either. What about adding this to the documentation of delete if there is no other (planned) way to build such query?

**Comment by tathougies** [comment]
Sure, we can add it to the documentation.

**Comment by oderwat** [comment]
@tathougies so there is no other way for an query without a where clause I guess? I can create a PR for  the documentation addition. I just wasn't sure if there is no other way than this work around.

**Comment by 3noch** [comment]
IMO this is not a workaround. It's a safety feature. You almost never want to delete without a where clause, so having a DSL that forces you to write a where clause seems better to me.

**Comment by tathougies** [comment]
@oderwat  That is correct, there is no other way to DELETE without a where clause. As@3noch says, it's not something that should be done accidentally, so it's better to make sure such an intention is explicitly stated.

**Comment by oderwat** [comment]
I was originally searching for TRUNCATE but that is (seems) not yet implemented. So DELETE (all) was just something which could already be done. It still is not working for what I needed it because it wont reset the auto increment values. So I can't use Beam for that. Which is only a minor problem though.

Being forced to create "WHERE TRUE" does indeed increase the safety. But having a DSL construct to state that I want no WHERE part seems also natural for me. This is why I called it a work around. Our real code uses such DELETE and even UPDATE queries (mostly for deleting / touching caches or while running tests). I agree: The const construct will do for that.

What I really wanted to know was if there is something to omit the WHERE or not, because when I extend the documentation that it needs the const true part it would be "wrong" if there is another way.
