### ISSUE TITLE
Error in Tutorial Part 1

### ISSUE THREAD

**Issue by mcbahson** [tathougies/beam#375]
When typing

```
User "john@example.com" "John" "Smith" "password!" :: User
```
I get the following:

> Couldn't match type ‘Ghci2.User’ with ‘UserT Identity’

Full i/o here:
https://gist.github.com/mcbahson/2b256ac43df6c7e0a891e06c38340b6e

**Comment by kmicklas** [comment]
Before you define [`type User = UserT Identity`](https://gist.github.com/mcbahson/2b256ac43df6c7e0a891e06c38340b6e#file-error-txt-L45), you [define a data type `User`](https://gist.github.com/mcbahson/2b256ac43df6c7e0a891e06c38340b6e#file-error-txt-L39) with a constructor called `User`, which shadows the `User` constructor of `UserT`. So when you write `User "john@example.com" "John" "Smith" "password!" :: User`, you are using the *second* datatype's constructor but the intended type alias for the type assertion.

I think it should work if you remove that second data type definition that doesn't have the `f` parameter. Feel free to reopen if you're still having issues!
