### ISSUE TITLE
beam-migrate defaultTo_ with expressions

### ISSUE THREAD

**Issue by JustinChristensen** [tathougies/beam#389]
Does `defaultTo_` support expressions? I don't see how I'd be able to create a table with `DEFAULT uuid_generate_v4()` as shown here: https://stackoverflow.com/questions/33274291/postgresql-uuid-or-sequence-for-primary-key.

**Comment by tathougies** [comment]
Yes, `defaultTo_` supports expressions.

`defaultTo_ (pgCryptoGenRandomUUID (pgCryptoExtension db))`

**Comment by JustinChristensen** [comment]
Thank you!

**Comment by JustinChristensen** [comment]
Unfortunately that didn't work. 

https://gist.github.com/JustinChristensen/b15e3305e2345e3af29326428b7c11bf

Using:

beam-core 0.8.0.0
beam-migrate 0.4.0.1
beam-postgres 0.4.0.0
