### ISSUE TITLE
Left-join on nullable key

### ISSUE THREAD

**Issue by ondrap** [tathougies/beam#397]
Let's say I have 2 tables:
```sql
CREATE TABLE users (
  userid serial primary key,
  username text not null
);
CREATE TABLE messages (
  msgid serial primary key,
  authorid int8 references users(userid) -- this can be null
);
```

I want to list all messages with the `username` being as an optional column if the message has a non-null `authorid`. However, I was not able to come up with a solution - obviously I want a left join, but with `leftJoin_` the `userid` is an `Int` instead of `Maybe Int`. I ended up with:

```haskell
toMaybe_ :: QGenExpr ctxt Postgres s a -> QGenExpr ctxt Postgres s (Maybe a)
toMaybe_ (QExpr q) = QExpr q

msg <- all_ (_dbMessages myDb)
user <- leftJoin_' (all_ (_dbUsers myDb)) (\u -> toMaybe_ (u ^. userid) ==?. (msg ^. authorid))
pure (msg, user ^. username)
```

I wonder if there is a better way to do that or, alternatively, if `toMaybe_` could be added to the standard library.

**Comment by mulderr** [comment]
This `toMaybe_` looks like a specialized version of `just_` from `SqlJustable` which is in `beam-core`.

```haskell
class SqlJustable a b | b -> a where
  just_ :: a -> b
  nothing_ :: b

-- this instance in particular
instance Database.Beam.Backend.SQL.BeamSqlBackend be =>
         SqlJustable (QExpr be s a) (QExpr be s (Maybe a))
```

There is also an example of using `just_` in the [tutorial](https://tathougies.github.io/beam/tutorials/tutorial3/).

**Comment by ondrap** [comment]
Oh...thanks. I was searching quite a lot and somehow missed it.

**Comment by mulderr** [comment]
I did too so eventually I made a PR to add an example to the docs. Feel free to make it even more clear :)
