### ISSUE TITLE
Sqlite "INSERT OR IGNORE", "INSERT OR REPLACE" etc.

### ISSUE THREAD

**Issue by tmcl** [tathougies/beam#399]
SQLite supports various useful additions to the SQL INSERT statements:
* `INSERT OR IGNORE` succeeds even if it does nothing because constraints are not met.
* `INSERT OR REPLACE` inserts unless there's a duplicate, in which case it updates.

https://www.sqlite.org/lang_insert.html

These would be useful to avoid redundantly making explicit checks when the engine is already capable of dealing with them.

**Comment by kmicklas** [comment]
It does appear to me that upsert / insert on conflict is strictly more powerful than these. I'm closing this for now but if I'm mistaken or you think the upsert support is lacking in some way feel free to reopen it.
