### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by aspidites** [tathougies/beam#4]
I forked beam earlier today and did the minimum possible to get the example to work with MySQL. I still need to break everything off into a separate library which depends on beam, but wanted to see what else was required before I could be confident that my branch does that the original does. 

@tathougies, would you mind giving some guidance in that regard? There isn't a test suite, so I don't have anything pre-existing to go on. Another idea I had was to follow the tutorial, but using MySQL to see if I ran into any speed bumps. 

Also, I ended up creating a stack.yaml as I prefer it to cabal. Would you be interested in having a current stack.yaml in the main repo, or should I just keep in with my code?

**Comment by tathougies** [comment]
Just a heads up. Had to rewrite the git history to correct an incorrect e-mail (due to bad git setup on my local machine). You may have to clone a new copy of the repository, and redo your changes on top of it, via git format-patch and git apply. Sorry for the inconvenience :(

**Comment by aspidites** [comment]
Good thing I hadn't planned on doing legwork until this weekend :P. Even
then, I think I could have just generated a match manually. Thanks for the
heads up.

On Fri, Mar 11, 2016 at 12:21 PM, Travis Athougies <notifications@github.com
> wrote:

> Just a heads up. Had to rewrite the git history to correct an incorrect
> e-mail (due to bad git setup on my local machine). You may have to clone a
> new copy of the repository, and redo your changes on top of it, via git
> format-patch and git apply. Sorry for the inconvenience :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tathougies/beam/issues/4#issuecomment-195463487>.
>



-- 
Regards,
Edwin O Marshall (aspidites)
http://github.com/aspidites <https://github.com/aspidites>
http://bitbucket.org/aspidites <https://bitbucket.org/aspidites>
http://www.assembla.com/profile/aspidites?public=true

**Comment by aspidites** [comment]
@tathougies,
Finally got back around to this. Sorry for the delay. I think I'm going to be working on this as a series of separate PRs as follows:

- stack support
- introduce tests
- mysql support

I figure if I can write tests for how things currently work, writing new backends should be easier. 

Do you always intend for the sqlite backend to ship with the library, or does it make sense for that to be a separate package once there is more than one backend?

**Comment by aspidites** [comment]
@tathougies,

Sorry for the delay on this. School started and I completely forgot about it. I'm working on the tests now. I haven't written any yet, but I expect that writing a test case for every scenario covered in the tutorial should be a good jump off point.

**Comment by tathougies** [comment]
Finally got around to this... See the [beam-mysql](https://github.com/tathougies/beam-mysql) repository.
