### ISSUE TITLE
withDbModification analogue for beam-migrate?

### ISSUE THREAD

**Issue by tsuraan** [tathougies/beam#406]
I'm trying to port a library to using beam-migrate instead of postgresql-simple-migration, and hitting a wall with the final construction of the CheckedDatabaseSettings. I figured out the entity modification changes:

```haskell
tableMod ::
     EntityModification (DatabaseEntity be db) be (TableEntity MyTableT)
tableMod =
  modifyTable (\_ -> "mytable") $
  tableModification
    { _tableId = fieldNamed "tableid"
    }
```
becomes
```haskell
tableMod ::
     EntityModification (CheckedDatabaseEntity be db) be (TableEntity MyTableT)
tableMod =
  modifyCheckedTable (\_ -> "mytable") $
  checkedTableModification
    { _tableId = checkedFieldNamed "tableid"
    }
```
but I don't see how to change the Settings definition. Old way looks like this:
```haskell
db :: DatabaseSettings be Db
db =
  defaultDbSettings `withDbModification`
  dbModification
    { _dbMyTable = Tables.tableMod
    }
```
and I think the new way would be something like:
```haskell
db :: DatabaseSettings be Db
db = unCheckDatabase db'

checkedDb :: CheckedDatabaseSettings be Db
checkedDb =
  defaultMigratableDbSettings `withDbModification`
  dbModification
    { _dbMyTable = Tables.tableMod
    }
```
but that doesn't compile; looks like `withDbModification` can't be called on a checked settings, but I can't find any `withCheckedDbModification` or `checkedDbModifcation` anywhere, so what's the right thing to do here?

**Comment by kmicklas** [comment]
It should work if you specify `be` (e.g. `Postgres` or `Sqlite`). `defaultMigratableDbSettings ` doesn't easily work polymorphically.

**Comment by tsuraan** [comment]
Aha, changing the signatures to `(Checked)?DatabaseSettings Postgres Db` does the trick. Thanks!
