### ISSUE TITLE
Returning a record instead of a tuple from a query

### ISSUE THREAD

**Issue by SandiDusic** [tathougies/beam#412]
I want to join a few tables and get back a record (`FullMessage`) with the results. I know I can `return` tuples from the `Q` monad but I'd rather have a record.

The full schema is [here](https://gist.github.com/SandiDusic/c7fa503baf34f5b2c770c1df21e6eefe). Here's what I tried:

```
data FullMessageT f = FullMessage
    { _message :: MessageT f
    , _user :: UserT f
    , _reply :: MessageT (Nullable f)
    , _forward :: ForwardT (Nullable f)
    , _media :: MediaT (Nullable f)
    } deriving (Generic, Beamable)

type FullMessage = FullMessageT Identity

messagesFromContext 
    :: (Database be db, HasSqlEqualityCheck be Int, HasSqlEqualityCheck be Integer)
    => TelegramDb (DatabaseEntity be db)
    -> Int 
    -> Q be db s (FullMessageT (QExpr be s))
messagesFromContext db id = do
    message <- (all_ $ _telegramMessage db)
        & filter_ (\msg -> _messageContextID msg ==. val_ id)
    user <- join_ (_telegramUser db) $ 
        \user -> (just_ $ _userID user) ==. _messageFromID message
    reply <- leftJoin_ (all_ $ _telegramMessage db) $ 
        \reply -> (just_ $ _messageID reply) ==. _messageReplyMessageID message
    forward <- leftJoin_ (all_ $ _telegramForward db) $
        \fwd -> (just_ $ primaryKey fwd) ==. _messageForwardID message
    media <- leftJoin_ (all_ $ _telegramMedia db) $
        \media -> (just_ $ primaryKey media) ==. _messageMediaID message
    return $ FullMessage message user reply forward media

runQuery :: SqliteM b -> IO b
runQuery query = do
    conn <- open "data/export.db"
    runBeamSqliteDebug putStrLn conn query

chatToJson :: Int -> FilePath -> IO ()
chatToJson id file = do
    messages :: [FullMessage] <- runQuery
            $ messagesFromContext telegramDb id
            & select
            & runSelectReturningList
    encodeFile file $ messages
```

I get the following error:
```
No instance for (Database.Beam.Backend.SQL.Row.GFromBackendRow
                         Sqlite
                         (GHC.Generics.K1
                            GHC.Generics.R
                            (PrimaryKey
                               ForwardT
                               (Nullable (Nullable Database.Beam.Backend.Types.Exposed))))
                         (GHC.Generics.K1
                            GHC.Generics.R
                            (PrimaryKey ForwardT (Nullable (Nullable Identity)))))
        arising from a use of ‘runSelectReturningList’
```

It works without the `Nullable` fields (just `_message` and `_user`).

**Comment by kmicklas** [comment]
In the type error you can see that in the complete composite record you have multiple levels of `Nullable` composed (`(Nullable (Nullable Identity))`). SQL doesn't have any concept of multiple levels of nullability (like composing `Maybe`s in Haskell) so you probably want to restrict it to just one.

For reference see the [warning about `Maybe` tyes](https://github.com/tathougies/beam/blob/30b3704824a865008cd76ca9c02e2711fa59371a/docs/user-guide/models.md#maybe-types) in the user guide. In other places in Beam this sort of thing may still work (for example in individual columns), but it can lead to confusing semantics.

**Comment by SandiDusic** [comment]
I saw in the guide that `Nullable` will get nested, but I don't know how to circumvent that in this case. The constituent records (`Forward`, `Media` and `Message`) have to have optional fields, and these records have to be optional fields of the composite record. That's what the schema dictates. Does that mean it's just not possible to return a record here, I have to use tuples?

**Comment by tathougies** [comment]
I'm afraid tuples are the only way out. For now, at least.

Travis Athougies

**Comment by SandiDusic** [comment]
Alright, thanks
