### ISSUE TITLE
UNIQUE constraint for column

### ISSUE THREAD

**Issue by pdavidow** [tathougies/beam#425]
How do I make a non-primary-key column unique?

For example, I want `_groupName` to be unique in
```
data GroupT f = Group
  { _groupId :: C f Text   -- primary key
  , _groupName :: C f Text
  } 
```

**Comment by pdavidow** [comment]
Is the Unique column constraint simply relegated to the manual create-table sql command, with the result that Beam will never know about it (apparently with no negative repercussions)?

**Comment by kmicklas** [comment]
Closing this for now but feel free to reopen if you're still having issues!
