### ISSUE TITLE
Issues with DOUBLE PRECISION and Migration

### ISSUE THREAD

**Issue by fosskers** [tathougies/beam#431]
Hi there, I seem to have hit [something related to this PR](https://github.com/tathougies/beam/pull/240). I'm running with the following:
```
beam-core 0.8.0.0
beam-migrate 0.4.0.1
beam-sqlite 0.4.0.0
```
I have a table with a `Double` field (among other things). When I auto-create this table via `createSchema` or `autoMigrate` everything goes fine. Any subsequent attempts result in:
```
[(TableHasColumn Sqlite: Table QualifiedName Nothing "transactions" must have a column "transaction_gasPrice" of DOUBLE PRECISION)]
```
Note that a dump of the offending table within `sqlite3` gives:
```
sqlite> .dump transactions
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "transactions"("transaction_id" INTEGER NOT NULL , "transaction_chainId" INTEGER NOT NULL , "transaction_block__block_id" INTEGER NOT NULL , "transaction_creationTime" INTEGER NOT NULL , "transaction_ttl" INTEGER NOT NULL , "transaction_gasLimit" INTEGER NOT NULL , "transaction_gasPrice" DOUBLE PRECISION NOT NULL , "transaction_sender" VARCHAR NOT NULL , "transaction_nonce" VARCHAR NOT NULL , "transaction_requestKey" VARCHAR NOT NULL , PRIMARY KEY("transaction_id"));
COMMIT;
```
If I remove that `Double` field, the problem goes away and the `autoMigrate` succeeds every time.
Any thoughts? Thank you.

**Comment by fosskers** [comment]
Hi there, any thoughts on this?

**Comment by kmicklas** [comment]
I can confirm that the column gets created with type `DOUBLE PRECISION` but the constraint gets picked up as just `DOUBLE`:

```
TableHasColumn Sqlite: Table QualifiedName Nothing "test" must have a column "test" of DOUBLE
```

**Comment by fosskers** [comment]
For the record I'll state here that this issue happens only with the sqlite backend, and isn't present at all after a switch to postgres.

**Comment by kmicklas** [comment]
Yeah, it looks like an issue with `parseSqliteDataType`. I can try to put up a fix today.
