### ISSUE TITLE
StrictData & undefined in Database/Beam/Schema/Tables.hs

### ISSUE THREAD

**Issue by andreyk0** [tathougies/beam#434]
Hi! 
Can't find an explicit mention of it but does `beam` *require* laziness ?
We've flipped our "model" modules to have `StrictData` and bumped into this exception in one place.

Looking at Tables.hs more closely it seems that `undefined` is used in a few places in the code but so far I haven't noticed any explicit mention of laziness in the docs. If it *is* required, would it be possible to at least throw some more specific exception instead, warning people that they got there because of the strictness?

E.g. stack trace (this is with `beam-core-0.8.0.0` from stackage):
```
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:78:14 in base:GHC.Err
  undefined, called at ./Database/Beam/Schema/Tables.hs:734:57 in beam-core-0.8.0.0-F4CWR8FpudnDJJHEC24RSk:Database.Beam.Schema.Tables
CallStack (from -prof):
  Database.Beam.Schema.Tables.withConstraints.\ (Database/Beam/Schema/Tables.hs:734:47-65)
  Database.Beam.Schema.Tables.changeBeamRep.\ (Database/Beam/Schema/Tables.hs:624:60-71)
  Database.Beam.Schema.Tables.changeBeamRep (Database/Beam/Schema/Tables.hs:624:1-81)
  Database.Beam.Schema.Tables.withConstraints (Database/Beam/Schema/Tables.hs:(733,1)-(734,79))
  Database.Beam.Schema.Tables.CAF:withConstraints2 (<no location info>)

```
Thanks!

**Comment by kmicklas** [comment]
I think I fixed the specific issue you're running into in https://github.com/tathougies/beam/pull/413, so you'll need to update to `master` until we do another hackage release. Please reopen this if you find any more places where strict data doesn't work!
