### ISSUE TITLE
Postgres Angry over Concurrent Transactions

### ISSUE THREAD

**Issue by fosskers** [tathougies/beam#438]
I've hit a strange case where Postgres transactions appear to be mixing and/or interfering with one another. I have a lookup that looks like this:
```haskell
example :: Connection -> IO ()
example c = do
  m <- runBeamPostgres c $ do
    a <- runSelectReturningOne $ lookup_ (tableA database) (AId p)
    b <- runSelectReturningOne $ lookup_ (tableB database) (BId p)
    pure (void a <|> void b)
  -- ... Do something with the `m`.
```
Which works just fine when ran in one thread, but if I attempt to run more than one of this at once with the combinators from `async` or [`scheduler`](http://hackage.haskell.org/package/scheduler), my program crashes with:
```
WARNING:  there is already a transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is already a transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is already a transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is already a transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is already a transaction in progress
example-program: SqlError {sqlState = "34000", sqlExecStatus = FatalError, sqlErrorMsg = "cursor \"temp14\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}
```
Do you have any idea what could be happening here? Please and thank you. For the record I'm on:
```
> stack ls dependencies | grep post
beam-postgres 0.4.1.0
postgresql-libpq 0.9.4.2
postgresql-simple 0.6.2

> aura -Qs postgres
local/postgresql 12.2-1
    Sophisticated object-relational DBMS
local/postgresql-libs 12.2-1
    Libraries for use with PostgreSQL
```

**Comment by fosskers** [comment]
I have inserts in another function further down in the logic. If I run *that* function in more than one thread (but the lookups are still in 1), eventually I hit:
```
example-program: SqlError {sqlState = "25006", sqlExecStatus = FatalError, sqlErrorMsg = "cannot execute INSERT in a read-only transaction", sqlErrorDetail = "", sqlErrorHint = ""}
```

**Comment by 3noch** [comment]
You can't use the same connection in multiple threads.

**Comment by fosskers** [comment]
Oh, that's interesting. I have another module where I'm doing that just fine, but the transactions are all inserts.

**Comment by fosskers** [comment]
You were right! I picked `resource-pool` to manage multiple connections across the various threads. Thanks!
