### ISSUE TITLE
Control.Lense.TH.makeFields fails to compile for tables

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#59]
```haskell
{-# LANGUAGE TemplateHaskell #-}

import Control.Lens.TH (makeFields)
import Database.Beam

data ConfigT f = Config{
    _configTId :: Columnar f (Auto Int)
  } deriving Generic
makeFields ''ConfigT
```

produces

```
  * Illegal type synonym family application in instance:
     Columnar f_a2iSV (Auto Int)
  * In the instance declaration for
      'HasId (ConfigT f_a2iSV) (Columnar f_a2iSV) (Auto Int))'
```

I've tried with `Text` instead of `Auto Int` with the same result.

I'm using GHC 8.0.2.

**Comment by 3noch** [comment]
`makeFields` does work on the `Database` record, however.

**Comment by tathougies** [comment]
Does `makeLenses` work?

**Comment by 3noch** [comment]
Yep!

**Comment by tathougies** [comment]
Hmm.. I believe the way `makeFields` work, it is not possible to use it with beam at the current time, due to the `Columnar` type family and the restriction against type family instances. I'll make a note of this in the docs.
