### ISSUE TITLE
Documentation on Hackage

### ISSUE THREAD

**Issue by aidecoe** [tathougies/beam#6]
You've written a great tutorial on Beam, but still there's no API documentation. Could you add it, please?

**Comment by tathougies** [comment]
There is most certainly haddock documentation available, and which gets built on my local machine, but it seems that hackage is having issues building it (https://hackage.haskell.org/package/beam-0.3.2.0/reports/1).

I'm not familiar with how to upload docs to hackage. Are you?

**Comment by tathougies** [comment]
Docs are now on hackage:

* [beam-core](https://hackage.haskell.org/package/beam-core-0.6.0.0)
* [beam-migrate](https://hackage.haskell.org/package/beam-migrate)

etc.
