### ISSUE TITLE
Add runInsertReturningList, etc. to Postgres backend

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#63]
This would just be a convenient wrapper.

**Comment by tathougies** [comment]
Hmm? `runInsertReturningList` should already be usable from within the `Pg` monad? Also, `beam-postgres` has its own (more robust) `runInsertReturning` functionality.

**Comment by 3noch** [comment]
Oh I didn't see it in the BeamExtensions module. Thanks!
