### ISSUE TITLE
GHC Warnings

### ISSUE THREAD

**Issue by aspidites** [tathougies/beam#7]
I get quite a few GHC warnings when compiling beam. I suspect some (most) of them are caused by using an old version of GHC. I can address them, but didn't know what your version policy was. I see a few different options:
- keep things as is since it compiles
- use the CPP extension to conditionally import things based on GHC version
- fix warnings which would increase version bounds base (at the very least)

I'm OK contributing any of the above, of course.

**Comment by tathougies** [comment]
The latest version compiles with `-Wall -Werror' (with certain warnings turned off by module)
