### ISSUE TITLE
filtering an orderBy causes invalid SQL instead of type error

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#70]
I had a query like this:

```haskell
runSelectReturningList $ select $ limit_ 5 $ filter_ cond $ orderBy_ order $ all table
```

This produced incorrect SQL.

Switching the `filter_` and `orderBy_` clauses works as expected.

**Comment by tathougies** [comment]
I am *not* seeing this. Your query is correctly generating a subquery on my machine. I've tested on sqlite and postgres. Can you post more context?

**Comment by 3noch** [comment]
The syntax was rejected. I'll see if I can repro.

**Comment by 3noch** [comment]
I'm definitely still seeing this with latest `master`, but perhaps it's more involved. I recently saw it in the query monad style instead:

```haskell
select $ do
  la <- orderBy_ (\(la, _) -> desc_ $ la^.laCreatedUtc)
    $ filter_ (\la -> not_ (la^.laDeleted))
    $ all_ (db^.leadactivity)
  u <- all_ (db^.users)
  guard_ ((la^.leadactivityByUser) `references` u)
  pure (la, u)
```

Moving the `orderBy` out of the `do` fixed it.

**Comment by tathougies** [comment]
@3noch  Finally getting around to this. I've managed to reproduce the bug. Looks like projections are being built wrong in a corner case in `buildSql92Query`. I will investigate and push a fix.
