### ISSUE TITLE
Support CONCAT

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#75]
I'd like to be able to use `like_` on the result of `CONCAT`.

**Comment by 3noch** [comment]
If this is easy to add, please just point me to the right spot.

**Comment by tathougies** [comment]
@3noch Adding new functions is very easy. Firstly, you determine what SQL standard the function is a part of. I don't believe CONCAT is in SQL92. Then, you add an appropriate class method to the expression class that corresponds to the SQL version or SQL extension that CONCAT is part of.

For example, the `ABS` function is part of SQL92, so there is an `absE` function in `IsSql92ExpressionSyntax` in `beam-core/Database/Beam/Backend/SQL/SQL92.hs`. I believe `CONCAT` is part of SQL99. However, many backends support it that do not support sql99 completely. Thus, I would likely create a new class, `IsSql99ConcatExpressionSyntax` in `beam-core/Database/Beam/Backend/SQL/SQL99.hs` as a sub-class of `IsSql92ExpressionSyntax`.

It would look something like 

```haskell
class IsSql92ExpressionSyntax syntax =>
  IsSql99ConcatExpressionSyntax where
  concatE :: [ syntax ] -> syntax
```

Then, you would implement the `CONCAT` function in backends that support it. You do this by instantiating an instance of the class you created in each backend. These are in the files `beam-postgres/Database/Beam/Postgres/Syntax.hs` and `beam-sqlite/Database/Beam/Sqlite/Syntax.hs`. You would likely use the `CONCAT` function in postgres and the `||` operator in sqlite.

Both postgres and sqlite syntaxes basically allow you to build up the expression string using a limited set of builders. Let me know if this is confusing. For example, the `BIT_LENGTH` function in the postgres backend is written

```haskell
  bitLengthE x = PgExpressionSyntax (emit "BIT_LENGTH(" <> fromPgExpression x <> emit ")")
```

Which corresponds to the `BIT_LENGTH(x)` postgres expression.

Finally, you would add a publicly accessible `concat_` function in `beam-core/Database/Beam/Query/Combinators.hs`. This lifts the syntax functions into the `QExpr` type, and provides richer typing information.

For example, the `bitLengthE` class function has the corresponding `bitLength_` function defined in `Combinators.hs`:

```haskell
bitLength_ ::
  IsSql92ExpressionSyntax syntax =>
  QGenExpr context syntax s SqlBitString -> QGenExpr context syntax s Int
bitLength_ (QExpr x) = QExpr (bitLengthE x)
```

As you can see, we basically just wrap and unwrap the `QExpr` new type.

Let me know if you need any help. I'll be on the IRC channel all day.

Oh, and finally, if there's ever a function you need, but don't have, it's pretty trivial to just write it, using the [`customExpr_` combinator](http://tathougies.github.io/beam/user-guide/extensibility/).

**Comment by 3noch** [comment]
Thanks for the excellent help! When I have some time I'll try to tackle this. I have been using `customExpr_` for the time being and it works well.

One trick concerning `CONCAT` is that it takes a variable number of arguments. I haven't figured out how to do that with your SQL-generating DSL in `customExpr_`. At least for `CONCAT` it should be possible to take homogenous list of values/columns since it only works on text (if SQL lets you mix types, I think the extra strictness would be a welcome improvement rather than a problem).

**Comment by tathougies** [comment]
@3noch You can take a list, and just emit the right variable-arity expression using the builder syntax in each backend. You're right `customExpr_` doesn't support that right now.

**Comment by 3noch** [comment]
@tathougies If it simplifies things, I've realized that you can write `CONCAT(col1, CONCAT(col2, CONCAT(col3, "")))`. This has allowed me to use only a few `concat_` functions to get any arity for now.
