### ISSUE TITLE
Lower operator precedence of common infix functions

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#76]
Operators like `==.` have a precedence of 4 which makes them convenient in the presence of lens operators (e.g. `user^.userName ==. val_ "Jim"`). However, it looks like at least some of the other common infix functions, are using the default precedence of 9. So you end up with, e.g. ```(user^.userName) `like_` val_ "Jim"``` or ```(user^.userName) `in_` [val_ "Jim"]```).

**Comment by tathougies** [comment]
Do you have suggestions as to the precedence for each operator? Happy to accept PRs.

**Comment by 3noch** [comment]
I'm guessing you'd want the infix forms of `in_` and `like_`, etc. to be the same precedence as `==.`. I'm happy to submit PR if you like that idea.

**Comment by tathougies** [comment]
@3noch Just make sure the precedences are the same in relation to one another as the SQL standard
