### ISSUE TITLE
Data.Default instances

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#78]
What do you think about adding a dependency to `data-default` and providing `Default` instances to `Auto` and others?

**Comment by tathougies** [comment]
I don't really like `data-default`. I would be happy to add a `Monad`, `Monoid`, and `MonadPlus` instance though, which would give you `mempty` and `mzero`.

**Comment by 3noch** [comment]
It would have been convenient if `instance Monoid m => Default m where def = mempty` but alas. I suppose users can add orphans if they really want this.

**Comment by 3noch** [comment]
What types should get the new instances you suggested?

**Comment by tathougies** [comment]
Probably just `Auto`

**Comment by tathougies** [comment]
Added a `Monoid` instance for `Auto` in the latest master.
