### ISSUE TITLE
How to do `QGenExpr _ Int -> QGenExpr _ (Auto Int)`

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#80]
This seems like `just_` but it's for `Auto`. I have a table with an `Int` and I want to join it on a table based on PK. However, the PK is `Auto Int`. At the normal "record-level" this is easy, but I'm not sure how to do it in queries.

**Comment by tathougies** [comment]
Hm... good point. I can add something

**Comment by 3noch** [comment]
Any hints? I could take a stab at it.

**Comment by tathougies** [comment]
@3noch You should basically be able to use `unsafeRetype` to do this safely. In fact, the following would be a safe version of `unsafeRetype` (safe because of the type restriction).

```
auto_ :: QGenExpr ctxt syntax s a -> QGenExpr ctxt syntax s (Auto a)
auto_ = unsafeRetype
```

**Comment by 3noch** [comment]
Fantastic. Shall I add this somewhere in a PR? ;)

**Comment by tathougies** [comment]
@3noch Yes, if you would that would be great!
