### ISSUE TITLE
Postgres: citext support?

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#87]
Postgres has the `citext` extension which would map very conveniently to `CI Text`.

**Comment by 3noch** [comment]
It appears you already map `CI Text` to `TEXT`. I get decode errors when trying to use `citext`. How would I go about fixing that?

**Comment by 3noch** [comment]
And now I see that I'm just wrong. `postgresql-simple` handles this as it should.

**Comment by 3noch** [comment]
However,

**Comment by tathougies** [comment]
@3noch Can you clarify what you mean by 'SQL-support typeclass'?

**Comment by 3noch** [comment]
Sorry. I mean GHC couldn't find a type class that had an instance for serializing / deserializing `CI Text` values.

**Comment by tathougies** [comment]
I've added these instances in `beam-postgres`. You should be able to find them in the latest master, or on hackage.
