### ISSUE TITLE
Rule based table field modifications

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#89]
I use a different scheme for naming records than what Beam supports. Because of this I have to override almost all of my table fields. This gets old fast. However, if I could provide a function to specify how to do the renaming, I could remove all of the boilerplate. How hard would it be to allow the renaming rule to be overridden at a DB or table level?

**Comment by tathougies** [comment]
This wouldn't be hard at all actually. I'll take a look tomorrow.
