### ISSUE TITLE
`exists_` example produces incorrect SQL

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#91]
I had a query almost identical to this: https://github.com/tathougies/beam/blob/d3baf0c77b76b008ad34901b47a818ea79439529/Doc/03-ProductsAndOrders.lhs#L325-L328

However, it somehow clobbered the alias that differentiated `user` and `order` such that `_orderForUser order ==. pk user` became `t0.order_for_user__id = t0.id` (notice that both tables are `t0`).

I ended up refactoring to a `leftJoin_` over a filtered subselect and comparing for null.

**Comment by tathougies** [comment]
Good catch! I'll investigate
